// Create / update / delete Foundry JournalEntry + JournalEntryPage from
// vault-rendered HTML. Every document carries flags.vaults.{vaultId,path}
// so a single world can host multiple vaults without conflict.
//
// Everything here writes into the vault's JournalEntry compendium pack, not
// the world. See packs.mjs for why. The practical consequence for this file
// is that lookups are async — a pack's documents are fetched, not resident —
// and that the Foundry Folders forming the sidebar tree are pack-local.
//
// Document model: one JournalEntry per vault directory; every .md file in
// that directory becomes an embedded JournalEntryPage. The autogenerated
// `index.md` in each folder gets sort=0 so it shows first; siblings sort
// after by filename. A directory with no subdirectories is "leaf" — we
// skip making a Foundry Folder for it and place its JournalEntry directly
// in the parent's Folder, since the extra Foundry-Folder layer would just
// wrap a single entry with no other entries to group with.

import { MODULE_ID } from "./settings.mjs";
import { ensurePack, instanceUuid } from "./packs.mjs";
import { docNameFromBase } from "./foundry-base.mjs";
import { entryId, pageId, folderId, folderOfPath, instanceId } from "./ids.mjs";
import { transformHtmlForFoundry } from "./links.mjs";
import { escapeBraces } from "./util.mjs";

const INDEX_BASENAME = "index";
const NON_INDEX_SORT_BASE = 100000;

// Doc types instance.mjs's blank-doc form supports. Mirrored here (rather
// than imported from instance.mjs to avoid the circular dependency that
// would force) so we can derive a UUID-class hint from `foundry.base` for
// the in-page "Open in Foundry" link. See foundry-base.mjs for the parse;
// this file's own copy rejected priority lists, so the link disappeared for
// every page using one.

/**
 * Ensure a chain of nested Foundry folders exists matching the vault's
 * directory hierarchy under the vault's configured root folder. Returns
 * the deepest folder's id.
 */
async function ensureFolderChain(pack, vault, segments) {
  // No root folder inside the pack: the pack *is* the vault's container, and
  // wrapping its whole contents in a single folder named after it would add a
  // level every reader has to open before seeing anything.
  let parentId = null;
  let acc = `${vault.id}/__root__/${vault.rootFolder || vault.label || "Vault"}`;
  for (const seg of segments) {
    acc += "/" + seg;
    const fId = await folderId(vault.id, acc);
    await upsertFolder(pack, fId, seg, parentId);
    parentId = fId;
  }
  return parentId;
}

async function upsertFolder(pack, id, name, parentId) {
  const existing = pack.folders.get(id);
  if (existing) {
    if (existing.name !== name || existing.folder?.id !== parentId) {
      await existing.update({ name, folder: parentId });
    }
    return existing;
  }
  await Folder.create(
    { _id: id, name, type: pack.documentName, folder: parentId },
    { pack: pack.collection, keepId: true },
  );
  // A rejected folder is not thrown either, and ensureFolderChain returns the
  // id it *asked* for — so every entry beneath it would be created pointing at
  // a folder that doesn't exist and land at the pack root instead.
  const created = pack.folders.get(id);
  if (!created) throw new Error(`Folder ${id} ("${name}") was rejected on create`);
  return created;
}

/**
 * Build per-folder context from the manifest's logical .md paths so the
 * importer can:
 *   - know whether a directory has any subfolders (so leaf directories
 *     can collapse upward, skipping the redundant Foundry-Folder layer)
 *   - cheaply resolve a directory's display name (its trailing segment)
 *
 * Returned map is keyed by folder path (root = ""). Every directory that
 * contains a page or has descendants gets an entry; ancestors are walked
 * so subfolder presence propagates up.
 */
export function buildFolderInfo(mdPaths) {
  const map = new Map();
  const ensure = (folderPath) => {
    let info = map.get(folderPath);
    if (!info) {
      const segs = folderPath ? folderPath.split("/") : [];
      info = { hasSubfolders: false, displayName: segs[segs.length - 1] || "" };
      map.set(folderPath, info);
    }
    return info;
  };
  ensure("");
  for (const p of mdPaths) {
    const folderPath = folderOfPath(p);
    ensure(folderPath);
    // Mark every strict ancestor as having a subfolder. For a file at "" the
    // segs array is empty and this loop is a no-op.
    const segs = folderPath ? folderPath.split("/") : [];
    for (let i = 0; i < segs.length; i++) {
      ensure(segs.slice(0, i).join("/")).hasSubfolders = true;
    }
  }
  return map;
}

function isIndexFile(filename) {
  return filename.replace(/\.md$/i, "") === INDEX_BASENAME;
}

/**
 * Import (create or update) a single page. `path` is the logical .md path;
 * `body` is the rendered article HTML; `meta` carries per-page manifest
 * metadata (role, title, …); `folderInfo` is the precomputed map from
 * `buildFolderInfo` so we can decide leaf-collapse without re-walking
 * the full manifest per file.
 *
 * All files in the same directory share one JournalEntry — its id is
 * folder-keyed (see ids.mjs). The first call for a folder creates the
 * entry with the file's page; subsequent calls embed additional pages.
 */
export async function upsertFile(vault, path, body, index, meta, folderInfo, mediaRefs) {
  let html = await transformHtmlForFoundry(vault, body, index, mediaRefs);
  html = await appendInstanceDocLink(html, vault, path, meta);

  const segs = path.split("/");
  const filename = segs.pop();
  const folderPath = segs.join("/");
  const fInfo = folderInfo?.get(folderPath);
  // Leaf-collapse: a folder with no subfolders contributes a single
  // JournalEntry (which embeds all its pages), so wrapping it in a same-named
  // Foundry Folder adds nothing. Place the entry directly in the parent
  // Folder. Root files (folderPath === "") never collapse — there is no
  // parent to host them. Multi-page collapses just work: the entry already
  // hosts every page in the folder regardless.
  const leaf = !!fInfo && folderPath !== "" && !fInfo.hasSubfolders;
  const hostSegs = leaf ? segs.slice(0, -1) : segs;
  const pack = await ensurePack(vault, "JournalEntry");
  const folderFId = await ensureFolderChain(pack, vault, hostSegs);

  // Entry name is the directory's display name; the page name keeps the
  // page's own frontmatter title (or filename) so the page tab in Foundry
  // matches the wiki's header.
  const entryName = folderPath === ""
    ? (vault.rootFolder || vault.label || "Vault")
    : (fInfo?.displayName || segs[segs.length - 1] || "");
  const pageName = meta?.title || filename.replace(/\.md$/i, "");

  const eId = await entryId(vault.id, path);
  // foundry.id pins this page's JournalEntryPage to an explicit Foundry id
  // (16 chars [A-Za-z0-9], validated CLI-side). Lets external Foundry code
  // reference the page by a stable known id rather than the SHA1 we'd
  // otherwise compute. The parent JournalEntry id is folder-shared and
  // intentionally not overridable per page.
  const idOverride = meta?.foundry?.id;
  const pId = typeof idOverride === "string" && idOverride
    ? idOverride
    : await pageId(vault.id, path);

  const pageOwnership = pageOwnershipLevelFor(vault, meta?.role);

  const flags = { [MODULE_ID]: { vaultId: vault.id, path } };
  const pageData = {
    _id: pId,
    name: pageName,
    type: "text",
    text: { content: html, format: 1 /* HTML */ },
    sort: isIndexFile(filename) ? 0 : NON_INDEX_SORT_BASE,
    flags,
    // Ownership is set on the *page*, not the parent entry: in the
    // folder-as-entry model a single entry can host pages of different
    // tiers, and entry-level ownership would leak DM pages to players via
    // the default INHERIT on sibling pages. The entry's own ownership is
    // reconciled separately as the max of its pages' levels (so the entry
    // remains visible in the sidebar to anyone who can see at least one
    // page in it). See reconcileOwnership below.
    ...(pageOwnership !== null ? { ownership: { default: pageOwnership } } : {}),
  };

  const existing = await pack.getDocument(eId);
  if (existing) {
    const entryPatch = {};
    if (existing.name !== entryName) entryPatch.name = entryName;
    if (existing.folder?.id !== folderFId) entryPatch.folder = folderFId;
    if (Object.keys(entryPatch).length > 0) await existing.update(entryPatch);

    const existingPage = existing.pages.get(pId);
    if (existingPage) await existingPage.update(pageData);
    else {
      await existing.createEmbeddedDocuments("JournalEntryPage", [pageData], { keepId: true });
      // Same contract as the create below: a rejected embedded document is
      // reported to the GM and skipped, not thrown, so the page can be absent
      // with the promise resolved.
      if (!existing.pages.get(pId)) throw new Error(`JournalEntryPage ${pId} was rejected on create`);
    }
    return "modified";
  }

  await JournalEntry.create({
    _id: eId,
    name: entryName,
    folder: folderFId,
    pages: [pageData],
    flags,
    // Bootstrap the entry visible at the page's tier so player-visible
    // pages aren't hidden in the gap between create and the post-sync
    // reconcileOwnership pass. Mixed-tier folders converge to max(pages)
    // via reconcile.
    ...(pageOwnership !== null ? { ownership: { default: pageOwnership } } : {}),
  }, { pack: pack.collection, keepId: true });
  // create() resolving is not proof the document exists: Foundry validates in
  // ClientDatabaseBackend##preCreateDocumentArray and, on failure, notifies the
  // GM and continues past it — the batch completes and nothing was written.
  // Without this check the caller counts an "added" page that isn't there, and
  // records its hash as synced so it is never retried.
  if (!await pack.getDocument(eId)) throw new Error(`JournalEntry ${eId} was rejected on create`);
  return "added";
}

/**
 * Map a page's role tier to a numeric ownership level (the value that
 * goes in `ownership.default`), given the vault's configured dmRole.
 * Returns null when no gating is configured; callers leave the doc's
 * ownership untouched in that case (Foundry's default = GM-only).
 *
 * Ranks come straight from vault.knownRoles (lowest → highest, as reported
 * by the deploy manifest). Rank below dmRole → OBSERVER for everyone; rank
 * at-or-above dmRole → NONE (GM-only).
 */
function pageOwnershipLevelFor(vault, pageRole) {
  if (!vault.dmRole || !vault.knownRoles?.length) return null;
  const dmIdx = vault.knownRoles.indexOf(vault.dmRole);
  if (dmIdx < 0) return null;
  const pageIdx = pageRole ? vault.knownRoles.indexOf(pageRole) : -1;
  // Unknown / missing page role: treat as the lowest tier so the page lands
  // player-visible. Conservative the other way (default to GM-only) would
  // hide pages from older deploys whose manifest predates the role field.
  const effectiveIdx = pageIdx < 0 ? 0 : pageIdx;
  return effectiveIdx < dmIdx
    ? CONST.DOCUMENT_OWNERSHIP_LEVELS.OBSERVER
    : CONST.DOCUMENT_OWNERSHIP_LEVELS.NONE;
}

/**
 * Bring every entry in the vault's pack back in line with the manifest: the
 * folder it belongs in, and the ownership its pages should carry.
 *
 * One walk rather than the two this used to be. A pack's documents are
 * fetched rather than resident, so a second pass would mean downloading every
 * entry the vault owns all over again for the sake of a different field.
 *
 * Placement catches the leaf-collapse transitions: a folder that gained a
 * subfolder and should no longer collapse into its parent, and the reverse.
 * Ownership catches pages whose role changed without their body changing, so
 * they never appeared in `toUpsert`.
 *
 * The ownership half is worth doing even though a compendium does not enforce
 * it — a pack is GM-only whatever its documents say. It is what Foundry's
 * Import All carries into the world (it passes `clearOwnership: false`), and
 * the world is where per-page tiers can actually be enforced. Without it every
 * import would land GM-only regardless of role. See packs.mjs.
 *
 * Idempotent: no writes when the current state already matches.
 */
export async function reconcileEntries(vault, folderInfo, bodyMetaIndex) {
  const pack = await ensurePack(vault, "JournalEntry");
  // Every document in the pack is this vault's, so the flag check is not
  // about telling vaults apart any more. It is about leaving alone anything
  // the GM dropped into the pack by hand, which has no flag and should not be
  // silently re-filed or re-owned by a sync.
  const ours = (await pack.getDocuments())
    .filter((j) => j.getFlag(MODULE_ID, "vaultId") === vault.id);
  const gated = !!vault.dmRole && !!vault.knownRoles?.length;
  for (const entry of ours) {
    await reconcilePlacement(pack, vault, entry, folderInfo);
    if (gated) await reconcileOwnership(vault, entry, bodyMetaIndex);
  }
}

/**
 * `bodyMetaIndex` is keyed by `<path>.body.html` (what the manifest
 * advertises); pages flag their logical `<path>.md`, so we convert. Pages with
 * no matching meta (e.g. files removed from the manifest but not yet deleted
 * by this sync) are skipped.
 *
 * The entry's own ownership becomes max(page ownership) so it stays visible to
 * anyone who can see at least one page in it — in the folder-as-entry model a
 * single entry hosts pages of different tiers, and entry-level ownership alone
 * would leak a DM page through a public sibling.
 */
async function reconcileOwnership(vault, entry, bodyMetaIndex) {
  let entryMax = null;
  for (const page of entry.pages.contents) {
    const pPath = page.getFlag(MODULE_ID, "path");
    if (!pPath) continue;
    const meta = bodyMetaIndex.get(pPath.replace(/\.md$/i, ".body.html"));
    if (!meta) continue;
    const level = pageOwnershipLevelFor(vault, meta.role);
    if (level === null) continue;
    if (page.ownership?.default !== level) {
      try { await page.update({ ownership: { default: level } }); }
      catch (err) { console.warn(`Vaults | reconcile ownership ${pPath} → ${level} failed:`, err); }
    }
    if (entryMax === null || level > entryMax) entryMax = level;
  }
  if (entryMax !== null && entry.ownership?.default !== entryMax) {
    try { await entry.update({ ownership: { default: entryMax } }); }
    catch (err) { console.warn(`Vaults | reconcile entry ownership for ${entry.name} → ${entryMax} failed:`, err); }
  }
}

/** Re-file one entry into the folder its path currently maps to. */
async function reconcilePlacement(pack, vault, entry, folderInfo) {
  // Each entry's first page carries the source path on the vaults flag. The
  // folder we want is derived from that path's folderPath, with leaf-collapse
  // applied per the current folderInfo.
  const path = entry.pages.contents[0]?.getFlag(MODULE_ID, "path");
  if (!path) return;
  const segs = path.split("/");
  segs.pop();
  const folderPath = segs.join("/");
  const fInfo = folderInfo?.get(folderPath);
  const leaf = !!fInfo && folderPath !== "" && !fInfo.hasSubfolders;
  const expected = await ensureFolderChain(pack, vault, leaf ? segs.slice(0, -1) : segs);
  if ((entry.folder?.id ?? null) !== expected) {
    try { await entry.update({ folder: expected }); }
    catch (err) { console.warn(`Vaults | re-place ${path} → ${expected} failed:`, err); }
  }
}

/**
 * Delete the page for a vault path. Multiple pages can share an entry now
 * (one entry per directory), so only the embedded page goes away here. The
 * entry itself sticks around as long as any page remains; once the last
 * page is removed we tear down the entry too.
 */
export async function deleteFile(vault, path) {
  const eId = await entryId(vault.id, path);
  const pId = await pageId(vault.id, path);
  const pack = await ensurePack(vault, "JournalEntry");
  const entry = await pack.getDocument(eId);
  if (!entry) return;
  const page = entry.pages.get(pId);
  if (page) await page.delete();
  if (entry.pages.size === 0) await entry.delete();
}

/**
 * Append a small "Open in Foundry" link to the end of a page's article
 * HTML when the page declared a `foundry.base` (i.e., a derived doc was
 * instantiated for it). The link uses Foundry's `@UUID[…]{…}` enricher
 * syntax so it renders with the doc-type icon and clicks through to the
 * sheet. No-op for pages without an instance doc.
 *
 * Doc id derivation matches instance.mjs's resolution: an explicit
 * `foundry.id` overrides the SHA1-derived `instanceId`.
 */
async function appendInstanceDocLink(html, vault, path, meta) {
  const base = meta?.foundry?.base;
  const docName = docNameFromBase(base);
  if (!docName) return html;
  const idOverride = meta?.foundry?.id;
  const docId = typeof idOverride === "string" && idOverride
    ? idOverride
    : await instanceId(vault.id, path);
  const label = meta?.title || path.split("/").pop().replace(/\.md$/i, "");
  const uuid = instanceUuid(vault, docName, docId);
  return html + `\n<p class="vaults-instance-link"><em>Foundry document:</em> @UUID[${uuid}]{${escapeBraces(label)}}</p>`;
}
