// Create / update / delete Foundry JournalEntry + JournalEntryPage from
// vault-rendered HTML. Every document carries flags.vaults.{vaultId,path}
// so a single world can host multiple vaults without conflict.
//
// Document model: one JournalEntry per vault directory; every .md file in
// that directory becomes an embedded JournalEntryPage. The autogenerated
// `index.md` in each folder gets sort=0 so it shows first; siblings sort
// after by filename. A directory with no subdirectories is "leaf" — we
// skip making a Foundry Folder for it and place its JournalEntry directly
// in the parent's Folder, since the extra Foundry-Folder layer would just
// wrap a single entry with no other entries to group with.

import { MODULE_ID } from "./settings.mjs";
import { entryId, pageId, folderId, folderOfPath } from "./ids.mjs";
import { transformHtmlForFoundry } from "./links.mjs";

const INDEX_BASENAME = "index";
const NON_INDEX_SORT_BASE = 100000;

/**
 * Ensure a chain of nested Foundry folders exists matching the vault's
 * directory hierarchy under the vault's configured root folder. Returns
 * the deepest folder's id.
 */
async function ensureFolderChain(vault, segments) {
  const rootName = vault.rootFolder || vault.label || "Vault";
  const rootKey = `${vault.id}/__root__/${rootName}`;
  const rootFId = await folderId(vault.id, rootKey);
  await upsertFolder(rootFId, rootName, null);

  let parentId = rootFId;
  let acc = rootKey;
  for (const seg of segments) {
    acc += "/" + seg;
    const fId = await folderId(vault.id, acc);
    await upsertFolder(fId, seg, parentId);
    parentId = fId;
  }
  return parentId;
}

async function upsertFolder(id, name, parentId) {
  const existing = game.folders.get(id);
  if (existing) {
    if (existing.name !== name || existing.folder?.id !== parentId) {
      await existing.update({ name, folder: parentId });
    }
    return existing;
  }
  return Folder.create({ _id: id, name, type: "JournalEntry", folder: parentId }, { keepId: true });
}

/**
 * Build per-folder context from the manifest's logical .md paths so the
 * importer can:
 *   - know whether a directory has any subfolders (so leaf directories
 *     can collapse upward, skipping the redundant Foundry-Folder layer)
 *   - cheaply resolve a directory's display name (its trailing segment)
 *
 * Returned map is keyed by folder path (root = ""). Every directory that
 * contains a page or has descendants gets an entry; ancestors are walked
 * so subfolder presence propagates up. `pageCount` is computed but no
 * longer drives the collapse decision; kept as useful metadata.
 */
export function buildFolderInfo(mdPaths) {
  const map = new Map();
  const ensure = (folderPath) => {
    let info = map.get(folderPath);
    if (!info) {
      const segs = folderPath ? folderPath.split("/") : [];
      info = { pageCount: 0, hasSubfolders: false, displayName: segs[segs.length - 1] || "" };
      map.set(folderPath, info);
    }
    return info;
  };
  ensure("");
  for (const p of mdPaths) {
    const folderPath = folderOfPath(p);
    ensure(folderPath).pageCount++;
    // Mark every strict ancestor as having a subfolder. For a file at "" the
    // segs array is empty and this loop is a no-op.
    const segs = folderPath ? folderPath.split("/") : [];
    for (let i = 0; i < segs.length; i++) {
      ensure(segs.slice(0, i).join("/")).hasSubfolders = true;
    }
  }
  return map;
}

function isIndexFile(filename) {
  return filename.replace(/\.md$/i, "") === INDEX_BASENAME;
}

/**
 * Import (create or update) a single page. `path` is the logical .md path;
 * `body` is the rendered article HTML; `meta` carries per-page manifest
 * metadata (role, title, …); `folderInfo` is the precomputed map from
 * `buildFolderInfo` so we can decide leaf-collapse without re-walking
 * the full manifest per file.
 *
 * All files in the same directory share one JournalEntry — its id is
 * folder-keyed (see ids.mjs). The first call for a folder creates the
 * entry with the file's page; subsequent calls embed additional pages.
 */
export async function upsertFile(vault, path, body, index, meta, folderInfo) {
  const html = await transformHtmlForFoundry(vault, body, index);

  const segs = path.split("/");
  const filename = segs.pop();
  const folderPath = segs.join("/");
  const fInfo = folderInfo?.get(folderPath);
  // Leaf-collapse: a folder with no subfolders contributes a single
  // JournalEntry (which embeds all its pages), so wrapping it in a same-named
  // Foundry Folder adds nothing. Place the entry directly in the parent
  // Folder. Root files (folderPath === "") never collapse — there is no
  // parent to host them. Multi-page collapses just work: the entry already
  // hosts every page in the folder regardless.
  const leaf = !!fInfo && folderPath !== "" && !fInfo.hasSubfolders;
  const hostSegs = leaf ? segs.slice(0, -1) : segs;
  const folderFId = await ensureFolderChain(vault, hostSegs);

  // Entry name is the directory's display name; the page name keeps the
  // page's own frontmatter title (or filename) so the page tab in Foundry
  // matches the wiki's header.
  const entryName = folderPath === ""
    ? (vault.rootFolder || vault.label || "Vault")
    : (fInfo?.displayName || segs[segs.length - 1] || "");
  const pageName = meta?.title || filename.replace(/\.md$/i, "");

  const eId = await entryId(vault.id, path);
  // foundry.id pins this page's JournalEntryPage to an explicit Foundry id
  // (16 chars [A-Za-z0-9], validated CLI-side). Lets external Foundry code
  // reference the page by a stable known id rather than the SHA1 we'd
  // otherwise compute. The parent JournalEntry id is folder-shared and
  // intentionally not overridable per page.
  const idOverride = meta?.foundry?.id;
  const pId = typeof idOverride === "string" && idOverride
    ? idOverride
    : await pageId(vault.id, path);

  const flags = { [MODULE_ID]: { vaultId: vault.id, path } };
  const pageData = {
    _id: pId,
    name: pageName,
    type: "text",
    text: { content: html, format: 1 /* HTML */ },
    sort: isIndexFile(filename) ? 0 : NON_INDEX_SORT_BASE,
    flags,
  };

  const ownershipPatch = ownershipFor(vault, meta?.role);

  const existing = game.journal.get(eId);
  if (existing) {
    const entryPatch = {};
    if (existing.name !== entryName) entryPatch.name = entryName;
    if (existing.folder?.id !== folderFId) entryPatch.folder = folderFId;
    // Only push ownership when the page tier moved across the dmRole cutoff.
    // Avoids stomping over manual ownership tweaks the GM made on individual
    // entries during regular re-syncs.
    if (ownershipPatch && existing.ownership?.default !== ownershipPatch.default) {
      entryPatch.ownership = ownershipPatch;
    }
    if (Object.keys(entryPatch).length > 0) await existing.update(entryPatch);

    const existingPage = existing.pages.get(pId);
    if (existingPage) await existingPage.update(pageData);
    else await existing.createEmbeddedDocuments("JournalEntryPage", [pageData], { keepId: true });
    return "modified";
  }

  await JournalEntry.create({
    _id: eId,
    name: entryName,
    folder: folderFId,
    pages: [pageData],
    flags,
    ...(ownershipPatch ? { ownership: ownershipPatch } : {}),
  }, { keepId: true });
  return "added";
}

/**
 * Map a page's role tier to a JournalEntry ownership stanza, given the
 * vault's configured dmRole. Returns null when no gating is configured;
 * callers fall back to Foundry's default (GM-only) in that case.
 *
 * Ranks come straight from vault.knownRoles (lowest → highest, as reported
 * by the deploy manifest). Rank below dmRole → OBSERVER for everyone; rank
 * at-or-above dmRole → no override (so the entry remains GM-only).
 */
function ownershipFor(vault, pageRole) {
  if (!vault.dmRole || !vault.knownRoles?.length) return null;
  const dmIdx = vault.knownRoles.indexOf(vault.dmRole);
  if (dmIdx < 0) return null;
  const pageIdx = pageRole ? vault.knownRoles.indexOf(pageRole) : -1;
  // Unknown / missing page role: treat as the lowest tier so the page lands
  // player-visible. Conservative the other way (default to GM-only) would
  // hide pages from older deploys whose manifest predates the role field.
  const effectiveIdx = pageIdx < 0 ? 0 : pageIdx;
  if (effectiveIdx < dmIdx) {
    return { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OBSERVER };
  }
  return null;
}

/**
 * Re-place every existing entry into the folder it should currently live
 * in. Catches the trivial→non-trivial folder transition (a folder that
 * gained a subfolder and should no longer be leaf-collapsed into the
 * parent) and the reverse (a folder that lost its only subfolder and
 * should now collapse). Cheap: one pass over the vault's journals,
 * compares current folder.id to the expected one.
 *
 * Called from sync after every refresh; idempotent when nothing changed.
 */
export async function reconcileEntryPlacement(vault, folderInfo) {
  const ours = game.journal.contents.filter(
    (j) => j.getFlag(MODULE_ID, "vaultId") === vault.id,
  );
  for (const entry of ours) {
    // Each entry's first page carries the source path on the vaults flag.
    // The folder we want is derived from that path's folderPath (with
    // leaf-collapse applied per the current folderInfo).
    const firstPage = entry.pages.contents[0];
    const path = firstPage?.getFlag(MODULE_ID, "path");
    if (!path) continue;
    const segs = path.split("/");
    segs.pop();
    const folderPath = segs.join("/");
    const fInfo = folderInfo?.get(folderPath);
    const leaf = !!fInfo && folderPath !== "" && !fInfo.hasSubfolders;
    const hostSegs = leaf ? segs.slice(0, -1) : segs;
    const expectedFolderId = await ensureFolderChain(vault, hostSegs);
    if (entry.folder?.id !== expectedFolderId) {
      try { await entry.update({ folder: expectedFolderId }); }
      catch (err) { console.warn(`Vaults | re-place ${path} → ${expectedFolderId} failed:`, err); }
    }
  }
}

/**
 * Delete the page for a vault path. Multiple pages can share an entry now
 * (one entry per directory), so only the embedded page goes away here. The
 * entry itself sticks around as long as any page remains; once the last
 * page is removed we tear down the entry too.
 */
export async function deleteFile(vault, path) {
  const eId = await entryId(vault.id, path);
  const pId = await pageId(vault.id, path);
  const entry = game.journal.get(eId);
  if (!entry) return;
  const page = entry.pages.get(pId);
  if (page) await page.delete();
  if (entry.pages.size === 0) await entry.delete();
}

/**
 * Wipe every JournalEntry / Folder belonging to a given vault. Used when
 * the user removes a vault from the registry.
 */
export async function deleteVaultJournals(vaultId) {
  const journals = game.journal.contents.filter((j) => j.getFlag(MODULE_ID, "vaultId") === vaultId);
  for (const j of journals) await j.delete();
  // Folders don't carry the flag; they're identified by deterministic id.
  // We can't enumerate all of a vault's folders without walking, so just
  // delete the root folder if it's empty after journal removal.
  const folders = game.folders.contents.filter((f) => f.type === "JournalEntry");
  for (const f of folders.reverse()) {
    if (f.contents.length === 0 && f.children.length === 0) {
      // Conservative: only remove if it looks like it belonged to this vault
      // (root folder id is deterministic from vault id).
      const root = await folderId(vaultId, `${vaultId}/__root__/${f.name}`);
      if (f.id === root) await f.delete();
    }
  }
}
