// The Pages Function shipped to Cloudflare. Generated at build time with the
// role list and password hashes baked in. Validates session cookies, redirects
// to /login on a missing/expired cookie, and rewrites every request to the
// matching `_variants/<role>/` path before letting Pages serve it.

import { htmlAttr, htmlEscape } from "../escape.js";

/** A JSON file each role's variant ships, served as a download with a bearer for the caller's role written into it. */
export interface TokenDownload {
  /** URL path, and the file's path inside each role's variant. */
  path: string;
  /** Keys leading to an object in the file; every value of that object becomes the bearer. */
  tokens: string[];
  /** Bearer lifetime in seconds. */
  maxAge: number;
}

export interface AuthTemplateConfig {
  /** ordered low → high */
  roles: string[];
  download?: TokenDownload;
  /** role → encoded password hash ("iter:saltHex:hashHex"); only for roles above the default. */
  rolePasswords: Record<string, string>;
  /**
   * Optional Patreon overlay. When present, the Function adds a
   * /auth/patreon/start + /auth/patreon/callback flow that issues the
   * same session cookie as password login. The login page also gains a
   * "Sign in with Patreon" button. Independent of password auth: a role
   * can have either, both, or just a password.
   */
  patreon?: {
    clientId: string;
    campaignId: string;
    /** role name → Patreon tier ID (numeric string) */
    tiers: Record<string, string>;
  };
  /**
   * Optional generic OIDC overlay (any standards-compliant issuer: the
   * endpoints are resolved from discovery at configure time and baked in).
   * When present, the Function adds /auth/oidc/start + /auth/oidc/callback
   * and the login page gains a "Sign in with <displayName>" button. Role
   * assignment walks roleRules from the highest role down and grants the
   * first whose email/domain rule matches the identity's email.
   */
  oidc?: {
    displayName: string;
    clientId: string;
    authorizationEndpoint: string;
    tokenEndpoint: string;
    userinfoEndpoint: string;
    /** role name → email/domain rule; roles absent here stay password-only. */
    roleRules: Record<string, { emails?: string[]; domains?: string[] }>;
  };
}

export function renderAuthMiddleware(cfg: AuthTemplateConfig): string {
  const rolesLiteral = JSON.stringify(cfg.roles);
  const passwordsLiteral = JSON.stringify(cfg.rolePasswords);
  const patreonLiteral = JSON.stringify(cfg.patreon ?? null);
  const oidcLiteral = JSON.stringify(cfg.oidc ?? null);
  const downloadLiteral = JSON.stringify(cfg.download ?? null);

  return `// Auto-generated by the vaults CLI. Do not edit by hand.
// Roles, password hashes, and routing live here so the deployed Function
// is fully self-contained and doesn't need any other binding besides
// SESSION_SECRET (set via wrangler secret). When Patreon is configured,
// PATREON_CLIENT_SECRET also has to be set as a Wrangler secret; when
// OIDC is configured, OAUTH_CLIENT_SECRET likewise.

const ROLES = ${rolesLiteral};
const PASSWORDS = ${passwordsLiteral};
const PATREON = ${patreonLiteral};
const OIDC = ${oidcLiteral};
const DOWNLOAD = ${downloadLiteral};
const COOKIE_NAME = "vault_role";
// Non-HttpOnly companion cookie carrying the role name only; the auth check
// uses COOKIE_NAME (which is signed and HttpOnly), this one is purely for UI.
const DISPLAY_COOKIE_NAME = "vault_role_display";
const COOKIE_MAX_AGE = 60 * 60 * 24 * 7; // 7 days
// Tokens carry their purpose, so a session cookie cannot be replayed as a
// bearer or the other way round.
const TOKEN_TYPE_SESSION = "s";
const TOKEN_TYPE_BEARER = "b";
const PBKDF2_DEFAULT_ITERATIONS = 100000;
// Same shape as a real PBKDF2 hash (iterations:saltHex:hashHex with the
// expected lengths) but with all-zero salt + hash. Used to keep the
// /login response time consistent when the role doesn't exist or has no
// password — running PBKDF2 against this dummy means an attacker can't
// distinguish "role exists" from "role doesn't exist" by timing.
const DUMMY_PASSWORD_HASH = "100000:" + "0".repeat(32) + ":" + "0".repeat(64);

// ── Public middleware entry ────────────────────────────────────────────────

export const onRequest = async (ctx) => {
  return withSecurityHeaders(await handleRequest(ctx));
};

/**
 * Headers every response gets, added at the one exit so redirects and error
 * responses are covered too.
 */
function withSecurityHeaders(response) {
  const out = new Response(response.body, response);
  out.headers.set("Referrer-Policy", "no-referrer");
  out.headers.set("X-Content-Type-Options", "nosniff");
  return out;
}

const handleRequest = async (ctx) => {
  const { request, env, next } = ctx;
  const url = new URL(request.url);

  // CORS preflight, which a cross-origin fetch carrying an Authorization header
  // triggers. Allow * because a bearer gates the file, not the origin.
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders() });
  }

  // Block direct access to /_variants/<role>/*; those paths exist in storage
  // for the rewrite below, but exposing them would let anyone fetch any
  // variant's pages by guessing the role name.
  if (url.pathname.startsWith("/_variants/")) {
    return withCors(new Response("Not found", { status: 404 }), request);
  }

  // /login. POST validates a password and sets the session cookie. GET
  // serves the static login page from the deploy root; we have to pass it
  // through explicitly because the variant-rewrite below would otherwise
  // try to fetch /_variants/<role>/login (which doesn't exist).
  if (url.pathname === "/login") {
    if (request.method === "POST") return handleLogin(request, env);
    return next();
  }
  if (url.pathname === "/logout") {
    const headers = new Headers({ Location: safeNext(url.searchParams.get("next")) });
    // Emit the cookie-clear in two variants so we delete the cookie
    // regardless of which form was set: the new SameSite=None+Partitioned
    // form (used by current iframes / direct browsing), and the old
    // SameSite=Lax form (in case the cookie predates the partition switch).
    for (const name of [COOKIE_NAME, DISPLAY_COOKIE_NAME]) {
      for (const variant of clearCookieVariants(name)) {
        headers.append("Set-Cookie", variant);
      }
    }
    return new Response(null, { status: 302, headers });
  }

  // /auth/patreon/* — only mounted when the build saw a Patreon config.
  // Issues the same signed session cookie as password login on success;
  // failure paths bounce back to /login with an error param.
  if (PATREON) {
    if (url.pathname === "/auth/patreon/start" && request.method === "GET") {
      return handlePatreonStart(request, env);
    }
    if (url.pathname === "/auth/patreon/callback" && request.method === "GET") {
      return handlePatreonCallback(request, env);
    }
  }

  // /auth/oidc/* — only mounted when the build saw an OIDC config with at
  // least one role rule. Same session-cookie contract as password login.
  if (OIDC) {
    if (url.pathname === "/auth/oidc/start" && request.method === "GET") {
      return handleOidcStart(request, env);
    }
    if (url.pathname === "/auth/oidc/callback" && request.method === "GET") {
      return handleOidcCallback(request, env);
    }
  }

  if (DOWNLOAD && url.pathname === DOWNLOAD.path) {
    return withCors(await handleDownload(request, env), request);
  }

  // Skip rewriting for static-asset paths that don't have a per-role variant.
  // Anything outside the variant tree (images, css, login page, search index
  // for the default role on root, etc.) is served as-is by Pages.
  if (isSharedAsset(url.pathname)) return next();

  // Determine the user's role from the session cookie (default = lowest).
  const role = await readRole(request, env);

  // env.ASSETS canonicalizes URLs (strips .html, strips index.html, redirects
  // with 308s); passing those redirects through to the browser would expose
  // the /_variants/<role>/ path, which the guard at the top of this function
  // explicitly blocks. So: rewrite to a clean URL, and if ASSETS still returns
  // a redirect, follow it server-side instead of leaking it to the client.
  const target = "/_variants/" + role + (url.pathname === "/" ? "/" : url.pathname);
  let rewritten = new Request(new URL(target, url.origin).toString(), request);
  let response = await env.ASSETS.fetch(rewritten);
  if (response.status >= 300 && response.status < 400) {
    const location = response.headers.get("Location");
    if (location && location.startsWith("/_variants/")) {
      rewritten = new Request(new URL(location, url.origin).toString(), request);
      response = await env.ASSETS.fetch(rewritten);
    }
  }

  // Replace bare 404s with the variant's styled 404 page so the reader stays
  // inside the site (sidebar, search, sitemap intact). Only HTML navigation
  // requests get the page; asset/API requests get the bare 404 unchanged.
  if (response.status === 404 && wantsHtml(request)) {
    const fallback = await env.ASSETS.fetch(new URL("/_variants/" + role + "/404.html", url.origin).toString());
    if (fallback.ok) {
      return withCors(new Response(await fallback.text(), {
        status: 404,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }), request);
    }
  }
  return withCors(response, request);
};

// Headers for cross-origin fetches that carry a bearer. Origin: * is safe
// because the bearer gates each file, not the origin.
function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
    "Access-Control-Allow-Headers": "Authorization, Content-Type",
    "Access-Control-Max-Age": "86400",
    "Vary": "Origin",
  };
}

function withCors(response, request) {
  if (!request.headers.get("Origin")) return response;
  // Response from env.ASSETS.fetch is immutable; clone before mutating.
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(corsHeaders())) headers.set(k, v);
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

function wantsHtml(request) {
  const accept = request.headers.get("Accept") || "";
  return accept.includes("text/html") || accept === "*/*" || accept === "";
}

// ── Login ─────────────────────────────────────────────────────────────────

async function handleLogin(request, env) {
  const form = await request.formData();
  const role = String(form.get("role") || "");
  const password = String(form.get("password") || "");
  const next = safeNext(form.get("next"));

  // Generic "auth_failed" error for both "no such role / no password set"
  // and "wrong password" branches — distinct codes would let an attacker
  // enumerate which roles exist and which have passwords. Constant-time
  // PBKDF2 comparison handles the timing side; this handles the message
  // side. Run verifyPassword against a dummy hash on the no-role branch
  // so the response time profile stays roughly the same.
  const passwordHash = (ROLES.includes(role) && PASSWORDS[role])
    ? PASSWORDS[role]
    : DUMMY_PASSWORD_HASH;
  const ok = await verifyPassword(password, passwordHash);
  if (!ok || !ROLES.includes(role) || !PASSWORDS[role]) {
    return loginRedirect(next, "auth_failed");
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  return new Response(null, { status: 302, headers });
}

// Sanitise a 'next' redirect target. Only same-origin relative paths are
// allowed; anything else (absolute URLs, protocol-relative '//evil.com',
// the protected /_variants/ tree) is replaced with '/'. Prevents the login
// and logout endpoints from being weaponised as open redirects.
function safeNext(value) {
  const s = typeof value === "string" ? value : "";
  if (!s.startsWith("/")) return "/";
  if (s.startsWith("//")) return "/";
  if (s.startsWith("/_variants/")) return "/";
  return s;
}

function loginRedirect(next, error) {
  const url = "/login.html?error=" + encodeURIComponent(error) + "&next=" + encodeURIComponent(next);
  return new Response(null, { status: 302, headers: { Location: url } });
}

/** The token carries the caller's own role, so it grants nothing they could not already fetch with their cookie. */
async function handleDownload(request, env) {
  const url = new URL(request.url);
  const role = await readRole(request, env);
  // Fetched rather than passed through: the body is edited, and the caller must not choose the role.
  const built = await env.ASSETS.fetch(new Request(
    new URL("/_variants/" + role + DOWNLOAD.path, url.origin).toString(), request));
  if (!built.ok) return built;

  const file = await built.json();
  let slots = file;
  for (const key of DOWNLOAD.tokens) slots = slots?.[key];
  if (slots) {
    const token = await signToken(role, env.SESSION_SECRET, DOWNLOAD.maxAge, TOKEN_TYPE_BEARER);
    for (const key of Object.keys(slots)) slots[key] = token;
  }
  // Indented: this is a file a reader downloads, opens and sometimes edits.
  return new Response(JSON.stringify(file, null, 2), {
    headers: {
      "content-type": "application/json",
      "content-disposition": 'attachment; filename="' + DOWNLOAD.path.split("/").pop() + '"',
      "cache-control": "no-store",
    },
  });
}

// These two helpers are intentionally inline and not imported: this file
// generates a Cloudflare Pages Function as a string template, so the
// emitted worker can't \`import\` from cli/src/escape.ts at runtime. Keep the
// behaviour in sync with the canonical helpers in cli/src/escape.ts; the
// \`auth-template escape helpers stay in sync\` test in
// cli/test/handlers.test.ts asserts the source strings match.
function escHtml(s) { return String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c])); }
function escAttr(s) { return String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

// ── Patreon OAuth (optional, additive to password login) ─────────────────
// Bound only when PATREON !== null (i.e. the build saw a configured
// patreon block with at least one role mapped to a tier). Issues the same
// signed session cookie as password login on success; bounces back to
// /login with an error param on failure. CSRF state rides through a short-
// lived signed cookie so the callback can verify the round-trip.

// Shared by the Patreon and OIDC flows; only one OAuth round-trip can be in
// flight per browser at a time, and the state UUID check keeps a callback
// from one flow from completing the other's.
const STATE_COOKIE = "vault_oauth_state";
const STATE_TTL = 600; // 10 minutes — long enough for the user to authorise

async function handlePatreonStart(request, env) {
  if (!env.PATREON_CLIENT_SECRET) {
    return new Response("Patreon login is misconfigured: PATREON_CLIENT_SECRET secret is missing.", { status: 500 });
  }
  const url = new URL(request.url);
  const next = safeNext(url.searchParams.get("next"));
  // Bind state to next so a forged callback can't drop the user on an
  // attacker-chosen URL post-login. The signed cookie carries both back.
  const stateValue = crypto.randomUUID();
  const stateCookie = await signStateCookie({ state: stateValue, next }, env.SESSION_SECRET);

  const redirectUri = url.origin + "/auth/patreon/callback";
  const authorize = new URL("https://www.patreon.com/oauth2/authorize");
  authorize.searchParams.set("response_type", "code");
  authorize.searchParams.set("client_id", PATREON.clientId);
  authorize.searchParams.set("redirect_uri", redirectUri);
  authorize.searchParams.set("scope", "identity identity.memberships");
  authorize.searchParams.set("state", stateValue);

  const headers = new Headers({ Location: authorize.toString() });
  headers.append("Set-Cookie", stateCookie);
  return new Response(null, { status: 302, headers });
}

async function handlePatreonCallback(request, env) {
  if (!env.PATREON_CLIENT_SECRET) {
    return loginRedirect("/", "patreon_misconfigured");
  }
  const url = new URL(request.url);
  const code = url.searchParams.get("code");
  const state = url.searchParams.get("state");
  if (!code || !state) return loginRedirect("/", "patreon_failed");

  const stateData = await readStateCookie(request, env.SESSION_SECRET);
  // Always clear the state cookie regardless of outcome.
  const clearState = clearCookieVariants(STATE_COOKIE);

  if (!stateData || stateData.state !== state) {
    const headers = new Headers({ Location: "/login?error=patreon_state_mismatch" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }
  const next = stateData.next || "/";

  // Exchange code → access token. The token is short-lived; we don't store
  // it. Only used once, immediately, to look up the visitor's memberships.
  let access;
  try {
    access = await patreonExchangeCode(code, url.origin + "/auth/patreon/callback", env.PATREON_CLIENT_SECRET);
  } catch (err) {
    console.warn("Patreon token exchange failed:", err);
    const headers = new Headers({ Location: "/login?error=patreon_token_exchange" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  let identity;
  try { identity = await patreonFetchIdentity(access); }
  catch (err) {
    console.warn("Patreon identity fetch failed:", err);
    const headers = new Headers({ Location: "/login?error=patreon_identity" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const role = matchHighestRole(identity, PATREON.campaignId, PATREON.tiers);
  if (!role) {
    // Authenticated, but no qualifying tier on this campaign. Send them
    // back to /login with a specific error so the UI can explain.
    const headers = new Headers({ Location: "/login?error=patreon_no_tier&next=" + encodeURIComponent(next) });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  for (const v of clearState) headers.append("Set-Cookie", v);
  return new Response(null, { status: 302, headers });
}

/**
 * Walk the visitor's identity payload, find memberships scoped to OUR
 * campaign, and return the highest-ranked role whose mapped tier ID
 * appears in the visitor's currently-entitled tiers. Returns null if no
 * tier matches — the visitor may be a patron of someone else, or the
 * creator's own account, or just not entitled to any mapped tier.
 */
function matchHighestRole(identity, campaignId, tiers) {
  const memberships = (identity?.included || []).filter((it) => it.type === "member");
  // Filter to memberships on our campaign (Patreon nests campaign under relationships).
  const ourCampaignMemberships = memberships.filter((m) => {
    const camp = m.relationships?.campaign?.data;
    return camp && camp.type === "campaign" && String(camp.id) === String(campaignId);
  });
  const entitledTierIds = new Set();
  for (const m of ourCampaignMemberships) {
    const ents = m.relationships?.currently_entitled_tiers?.data || [];
    for (const t of ents) if (t.type === "tier") entitledTierIds.add(String(t.id));
  }
  if (entitledTierIds.size === 0) return null;
  // Roles are ordered low → high; iterate from highest to find the best match.
  for (let i = ROLES.length - 1; i >= 0; i--) {
    const r = ROLES[i];
    const tier = tiers[r];
    if (tier && entitledTierIds.has(String(tier))) return r;
  }
  return null;
}

async function patreonExchangeCode(code, redirectUri, clientSecret) {
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    code,
    client_id: PATREON.clientId,
    client_secret: clientSecret,
    redirect_uri: redirectUri,
  });
  const res = await fetch("https://www.patreon.com/api/oauth2/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });
  if (!res.ok) throw new Error("token exchange status " + res.status);
  const data = await res.json();
  if (!data.access_token) throw new Error("no access_token in response");
  return data.access_token;
}

async function patreonFetchIdentity(accessToken) {
  // We need the visitor's memberships AND, for each membership, which tiers
  // they're currently entitled to. Patreon's JSON:API include syntax pulls
  // both into one round-trip.
  const url = new URL("https://www.patreon.com/api/oauth2/v2/identity");
  url.searchParams.set("include", "memberships,memberships.currently_entitled_tiers,memberships.campaign");
  url.searchParams.set("fields[member]", "patron_status");
  const res = await fetch(url.toString(), {
    headers: { Authorization: "Bearer " + accessToken },
  });
  if (!res.ok) throw new Error("identity status " + res.status);
  return await res.json();
}

// ── OIDC OAuth (optional, additive to password login) ────────────────────
// Bound only when OIDC !== null (i.e. the build saw an oidc block with at
// least one role rule). Standard authorization-code flow with PKCE (S256):
// the code_verifier rides in the signed state cookie, the challenge goes to
// the authorization endpoint. Identity comes from the userinfo endpoint;
// the visitor's email is matched against per-role email/domain rules.

async function handleOidcStart(request, env) {
  if (!env.OAUTH_CLIENT_SECRET) {
    return new Response("OIDC login is misconfigured: OAUTH_CLIENT_SECRET secret is missing.", { status: 500 });
  }
  const url = new URL(request.url);
  const next = safeNext(url.searchParams.get("next"));
  const stateValue = crypto.randomUUID();
  const verifier = base64UrlEncode(crypto.getRandomValues(new Uint8Array(32)));
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier));
  const challenge = base64UrlEncode(new Uint8Array(digest));
  const stateCookie = await signStateCookie({ state: stateValue, next, verifier }, env.SESSION_SECRET);

  const authorize = new URL(OIDC.authorizationEndpoint);
  authorize.searchParams.set("response_type", "code");
  authorize.searchParams.set("client_id", OIDC.clientId);
  authorize.searchParams.set("redirect_uri", url.origin + "/auth/oidc/callback");
  authorize.searchParams.set("scope", "openid email");
  authorize.searchParams.set("state", stateValue);
  authorize.searchParams.set("code_challenge", challenge);
  authorize.searchParams.set("code_challenge_method", "S256");

  const headers = new Headers({ Location: authorize.toString() });
  headers.append("Set-Cookie", stateCookie);
  return new Response(null, { status: 302, headers });
}

async function handleOidcCallback(request, env) {
  if (!env.OAUTH_CLIENT_SECRET) {
    return loginRedirect("/", "oidc_misconfigured");
  }
  const url = new URL(request.url);
  const code = url.searchParams.get("code");
  const state = url.searchParams.get("state");
  if (!code || !state) return loginRedirect("/", "oidc_failed");

  const stateData = await readStateCookie(request, env.SESSION_SECRET);
  // Always clear the state cookie regardless of outcome.
  const clearState = clearCookieVariants(STATE_COOKIE);

  if (!stateData || stateData.state !== state) {
    const headers = new Headers({ Location: "/login?error=oidc_state_mismatch" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }
  const next = stateData.next || "/";

  // Exchange code → access token; used once, immediately, for userinfo.
  let access;
  try {
    access = await oidcExchangeCode(code, url.origin + "/auth/oidc/callback", env.OAUTH_CLIENT_SECRET, stateData.verifier);
  } catch (err) {
    console.warn("OIDC token exchange failed:", err);
    const headers = new Headers({ Location: "/login?error=oidc_token_exchange" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  let email;
  try { email = await oidcFetchEmail(access); }
  catch (err) {
    console.warn("OIDC userinfo fetch failed:", err);
    const headers = new Headers({ Location: "/login?error=oidc_identity" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const role = matchOidcRole(email, OIDC.roleRules);
  if (!role) {
    // Authenticated, but no rule grants this email a role.
    const headers = new Headers({ Location: "/login?error=oidc_no_role&next=" + encodeURIComponent(next) });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  for (const v of clearState) headers.append("Set-Cookie", v);
  return new Response(null, { status: 302, headers });
}

// Duplicated from cli/src/render/oidc-match.ts — the worker can't import TS
// modules, so keep the two copies in sync. Matching is exact and case-
// insensitive; a domain rule matches only the exact domain after the last
// '@' (subdomains are not implied).
function matchOidcRole(email, roleRules) {
  const at = email.lastIndexOf("@");
  if (at < 0) return null;
  const lower = email.toLowerCase();
  const domain = lower.slice(at + 1);
  for (let i = ROLES.length - 1; i >= 0; i--) {
    const rule = roleRules[ROLES[i]];
    if (!rule) continue;
    if ((rule.emails || []).some((e) => e.toLowerCase() === lower)) return ROLES[i];
    if (domain && (rule.domains || []).some((d) => d.toLowerCase() === domain)) return ROLES[i];
  }
  return null;
}

async function oidcExchangeCode(code, redirectUri, clientSecret, verifier) {
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    code,
    client_id: OIDC.clientId,
    client_secret: clientSecret,
    redirect_uri: redirectUri,
    code_verifier: verifier || "",
  });
  const res = await fetch(OIDC.tokenEndpoint, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });
  if (!res.ok) throw new Error("token exchange status " + res.status);
  const data = await res.json();
  if (!data.access_token) throw new Error("no access_token in response");
  return data.access_token;
}

async function oidcFetchEmail(accessToken) {
  const res = await fetch(OIDC.userinfoEndpoint, {
    headers: { Authorization: "Bearer " + accessToken },
  });
  if (!res.ok) throw new Error("userinfo status " + res.status);
  const data = await res.json();
  if (typeof data.email !== "string" || !data.email) throw new Error("userinfo returned no email");
  return data.email;
}

function base64UrlEncode(bytes) {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\\+/g, "-").replace(/\\//g, "_").replace(/=+$/, "");
}

/** Inverse of base64UrlEncode for UTF-8 text. */
function base64UrlDecodeUtf8(s) {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/");
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}

// State cookie: stores { state, next } (plus the PKCE verifier for OIDC)
// signed with SESSION_SECRET, used to verify the OAuth callback came from
// our /start handler and not a forgery. Shared by both OAuth flows.
// Lifetime is short (STATE_TTL); kept distinct from the long-lived
// session cookie so a stolen state cookie can't impersonate a session.

async function signStateCookie(payload, secret) {
  const exp = Math.floor(Date.now() / 1000) + STATE_TTL;
  const data = JSON.stringify({ ...payload, exp });
  const sig = await hmac(data, secret);
  // The payload carries the next path, and btoa throws on any code point
  // above U+00FF — so a page whose name uses a non-Latin1 character
  // (Sunawi with a w-circumflex, Ordogok, Japanese) turned the /start
  // handler into an unhandled 500. Encode the UTF-8 bytes instead.
  // (No backticks in this comment: it is inside the middleware template.)
  const value = base64UrlEncode(new TextEncoder().encode(data)) + "." + sig;
  return STATE_COOKIE + "=" + value
    + "; Path=/; Secure; SameSite=Lax; HttpOnly; Max-Age=" + STATE_TTL;
}

async function readStateCookie(request, secret) {
  const cookies = parseCookie(request.headers.get("Cookie") || "");
  const raw = cookies[STATE_COOKIE];
  if (!raw) return null;
  const dot = raw.lastIndexOf(".");
  if (dot < 0) return null;
  const dataB64 = raw.slice(0, dot);
  const sig = raw.slice(dot + 1);
  let data;
  try { data = base64UrlDecodeUtf8(dataB64); }
  catch { return null; }
  const expected = await hmac(data, secret);
  // Constant-time, matching verifyToken; a plain !== leaks the signature
  // byte-by-byte through response timing.
  if (!constantTimeEqual(sig, expected)) return null;
  let parsed;
  try { parsed = JSON.parse(data); }
  catch { return null; }
  if (!parsed || typeof parsed.exp !== "number" || parsed.exp < Math.floor(Date.now() / 1000)) return null;
  return parsed;
}

// ── Cookie + role lookup ──────────────────────────────────────────────────

async function readRole(request, env) {
  const fallback = ROLES[0];
  if (!env.SESSION_SECRET) return fallback;

  // Authorization: Bearer <token>, from a download's spliced-in bearer.
  const auth = request.headers.get("Authorization") || "";
  const bearerMatch = /^Bearer\\s+(.+)$/i.exec(auth);
  if (bearerMatch) {
    const role = await verifyToken(bearerMatch[1], env.SESSION_SECRET, TOKEN_TYPE_BEARER);
    if (role && ROLES.includes(role)) return role;
  }

  const cookie = parseCookie(request.headers.get("Cookie") || "")[COOKIE_NAME];
  if (!cookie) return fallback;
  const role = await verifyToken(cookie, env.SESSION_SECRET, TOKEN_TYPE_SESSION);
  return role && ROLES.includes(role) ? role : fallback;
}

// Format: <role>.<expiryUnix>.<hmacHex>
async function signToken(role, secret, maxAgeSeconds, typ) {
  const exp = Math.floor(Date.now() / 1000) + maxAgeSeconds;
  const payload = typ + "." + role + "." + exp;
  const sig = await hmac(payload, secret);
  return payload + "." + sig;
}

async function signSessionCookie(role, secret) {
  const value = await signToken(role, secret, COOKIE_MAX_AGE, TOKEN_TYPE_SESSION);
  // SameSite=None + Partitioned (CHIPS): the cookie also persists inside a
  // cross-origin iframe, scoped per parent origin rather than shared across sites.
  return COOKIE_NAME + "=" + value
    + "; Path=/; HttpOnly; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE;
}

async function verifyToken(token, secret, expectedTyp) {
  const parts = token.split(".");
  // 4 parts is the typed form; 3 is the untyped one issued before session
  // cookies and bearers were distinguishable. Legacy tokens still verify, for
  // either purpose, so nobody is logged out by the upgrade — they age out on
  // their own within 90 days. Drop this branch after that.
  const legacy = parts.length === 3;
  if (parts.length !== 4 && !legacy) return null;
  const [typ, role, expStr, sig] = legacy ? [expectedTyp, ...parts] : parts;
  if (typ !== expectedTyp) return null;
  const exp = Number(expStr);
  if (!Number.isFinite(exp) || exp < Math.floor(Date.now() / 1000)) return null;
  const signed = legacy ? role + "." + expStr : typ + "." + role + "." + expStr;
  const expected = await hmac(signed, secret);
  return constantTimeEqual(sig, expected) ? role : null;
}

function clearCookieVariants(name) {
  // Browsers match cookies for deletion on (Path, Domain, Secure, SameSite,
  // Partitioned). A single Set-Cookie attempt only matches one configuration,
  // so we emit two; one that matches cookies set by the current
  // (SameSite=None+Partitioned) signSessionCookie, and one that matches the
  // older Lax form. Both are safe to send; the unmatched one is a no-op.
  const httpOnly = name === COOKIE_NAME ? "HttpOnly; " : "";
  return [
    name + "=; Path=/; " + httpOnly + "Secure; SameSite=None; Partitioned; Max-Age=0",
    name + "=; Path=/; " + httpOnly + "Secure; SameSite=Lax; Max-Age=0",
  ];
}

// ── Crypto primitives (Web Crypto API) ────────────────────────────────────

async function hmac(message, secretHex) {
  const keyBytes = fromHex(secretHex);
  const key = await crypto.subtle.importKey(
    "raw", keyBytes, { name: "HMAC", hash: "SHA-256" }, false, ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return toHex(new Uint8Array(sig));
}

async function verifyPassword(password, encoded) {
  const parts = encoded.split(":");
  if (parts.length !== 3) return false;
  const iterations = Number(parts[0]) || PBKDF2_DEFAULT_ITERATIONS;
  const salt = fromHex(parts[1]);
  const expected = fromHex(parts[2]);
  const key = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(password), { name: "PBKDF2" }, false, ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, hash: "SHA-256", iterations },
    key, expected.length * 8,
  );
  return constantTimeEqual(toHex(new Uint8Array(bits)), toHex(expected));
}

function constantTimeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function toHex(bytes) {
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += bytes[i].toString(16).padStart(2, "0");
  return s;
}

function fromHex(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function parseCookie(header) {
  const out = {};
  for (const part of header.split(/;\\s*/)) {
    const eq = part.indexOf("=");
    if (eq > 0) out[part.slice(0, eq)] = part.slice(eq + 1);
  }
  return out;
}

function isSharedAsset(pathname) {
  // Allowlist of root-served files that are intentionally public to every
  // visitor (no role gate). Everything else — including images, .body.html
  // fragments, .preview.json, the search index — goes through the variant
  // rewrite so role-restricted content is structurally unreachable on
  // under-tier deploys.
  //
  // SYNCHRONISATION POINT: every file the build writes to the deploy
  // ROOT (vs. into _variants/<role>/) must be listed here, otherwise it
  // 404s for every visitor. Build code that places root-level files:
  //   - styles.css / user.css        — build.ts (writeFile join(outputDir, ...))
  //   - _handlers.js / _handlers.css — build.ts (handler asset bundles, root)
  //   - katex/…                      — build.ts (copyKatexAssets; math vaults only)
  //   - login.html                   — build.ts (multi-role only)
  //   - favicon.ico                  — build.ts (buildFavicon)
  //   - functions/_middleware.js     — build.ts (multi-role only; not served)
  // If you add another, add it both here AND in build.ts.
  if (pathname === "/styles.css") return true;
  if (pathname === "/user.css") return true;
  if (pathname === "/_handlers.js") return true;
  if (pathname === "/_handlers.css") return true;
  if (pathname === "/katex/katex.min.css" || pathname.startsWith("/katex/fonts/")) return true;
  if (pathname === "/login.html") return true;
  if (pathname === "/favicon.ico" || pathname === "/favicon.svg") return true;
  if (pathname === "/robots.txt") return true;
  if (pathname === "/sitemap.xml") return true;
  return false;
}
`;
}

/**
 * Render `login.html` for a deploy, showing only the sign-in methods it
 * actually has.
 *
 * A role is reachable by password only if a hash was set for it; Patreon and
 * OIDC each carry their own role mappings. A deploy authenticating purely
 * through a provider therefore gets no password form and no role selector —
 * the selector only ever chose which password to check, so with one password
 * role (or none) it is noise, and with none it would be a form that cannot
 * succeed.
 */
export function renderLoginPage(opts: {
  /** Roles with a password hash, in tier order. */
  passwordRoles: string[];
  /** Roles mapped to a Patreon tier, empty when Patreon isn't configured. */
  patreonRoles: string[];
  /** OIDC provider display name, or null when OIDC isn't configured. */
  oidcDisplayName: string | null;
}): string {
  const { passwordRoles, patreonRoles, oidcDisplayName } = opts;

  let form = "";
  if (passwordRoles.length > 0) {
    // One password role means there is nothing to choose, so the role rides
    // as a hidden field and the visitor just types a password.
    const rolePicker = passwordRoles.length === 1
      ? `    <input type="hidden" name="role" value="${htmlAttr(passwordRoles[0]!)}">`
      : `    <label for="role">Role</label>\n`
        + `    <select id="role" name="role">`
        + passwordRoles.map((r) => `<option value="${htmlAttr(r)}">${htmlEscape(r)}</option>`).join("")
        + `</select>`;
    form = `  <form id="login-form" method="POST" action="/login">\n`
      + `${rolePicker}\n`
      + `    <label for="password">Password</label>\n`
      + `    <input id="password" type="password" name="password" autocomplete="current-password" required>\n`
      + `    <input type="hidden" name="next" id="next">\n`
      + `    <button type="submit">Sign in</button>\n`
      + `  </form>`;
  }

  // Replacer *functions*, not strings: a string replacement interprets `$&`
  // and friends, and oidcDisplayName is free text, so a provider named
  // "Acme $& Co" would splice the placeholder back into the page.
  const literal = (value: string) => () => value;
  return LOGIN_HTML
    .replace("__PASSWORD_FORM__", literal(form))
    .replace("__PATREON_ROLES_ATTR__", literal(patreonRoles.length > 0
      ? ` data-patreon-roles="${htmlAttr(patreonRoles.join(","))}"` : ""))
    .replace("__OIDC_ATTR__", literal(oidcDisplayName ? ` data-oidc="${htmlAttr(oidcDisplayName)}"` : ""));
}

const LOGIN_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sign in</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .login-card {
    max-width: 24rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .login-card h1 { margin: 0 0 1rem; font-size: 1.4rem; }
  .login-card label { display: block; font-size: 0.85rem; color: var(--muted); margin: 0.75rem 0 0.25rem; }
  .login-card select, .login-card input[type=password] {
    width: 100%; padding: 0.5rem 0.65rem; font: inherit; font-size: 0.95rem;
    background: var(--bg); color: var(--fg);
    border: 1px solid var(--rule); border-radius: 4px; outline: none;
  }
  .login-card select:focus, .login-card input:focus { border-color: var(--accent); box-shadow: 0 0 0 2px var(--wikilink-bg); }
  .login-card button {
    width: 100%; padding: 0.55rem 1rem; margin-top: 1rem; font: inherit;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px; cursor: pointer;
  }
  .login-error { color: #b94a3a; font-size: 0.85rem; margin: 0.75rem 0 0; }
  .login-divider {
    display: flex; align-items: center; gap: 0.6rem;
    margin: 1.25rem 0 1rem;
    font-size: 0.78rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.06em;
  }
  .login-divider::before, .login-divider::after {
    content: ""; flex: 1; height: 1px; background: var(--rule);
  }
  .patreon-btn {
    display: flex; align-items: center; justify-content: center; gap: 0.5rem;
    width: 100%; padding: 0.55rem 1rem; font: inherit; font-size: 0.95rem;
    background: #ff424d; color: white; border: 0; border-radius: 4px;
    cursor: pointer; text-decoration: none;
  }
  .patreon-btn:hover { filter: brightness(1.05); }
  .patreon-hint { color: var(--muted); font-size: 0.78rem; margin-top: 0.6rem; text-align: center; }
  .oidc-btn {
    display: flex; align-items: center; justify-content: center;
    width: 100%; padding: 0.55rem 1rem; font: inherit; font-size: 0.95rem;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px;
    cursor: pointer; text-decoration: none;
  }
  .oidc-btn:hover { filter: brightness(1.05); }
</style>
</head>
<body>
<div class="login-card"__PATREON_ROLES_ATTR____OIDC_ATTR__>
  <h1>Sign in</h1>
  <p id="err" class="login-error" hidden></p>
__PASSWORD_FORM__
  <div id="patreon-section" hidden>
    <div class="login-divider">or</div>
    <a id="patreon-btn" class="patreon-btn" href="#">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <circle cx="14.5" cy="9.5" r="6.5"/>
        <rect x="2" y="3" width="3.5" height="18"/>
      </svg>
      Sign in with Patreon
    </a>
    <p class="patreon-hint">
      Active patrons of the configured tiers can sign in directly. The role
      selector above only matters for password sign-in.
    </p>
  </div>
  <div id="oidc-section" hidden>
    <div class="login-divider">or</div>
    <a id="oidc-btn" class="oidc-btn" href="#">Sign in</a>
  </div>
</div>
<script>
  const params = new URLSearchParams(location.search);
  const next = params.get("next") || "/";
  // The password form is omitted entirely on a deploy where no role has a
  // password, so nothing here may assume its fields exist.
  const nextField = document.getElementById("next");
  if (nextField) nextField.value = next;
  const err = params.get("error");
  if (err) {
    const el = document.getElementById("err");
    const messages = {
      // Single message for any password-path failure — distinct error
      // codes would let an attacker enumerate which roles exist.
      auth_failed: "Invalid role or password.",
      patreon_state_mismatch: "Patreon sign-in expired or was tampered with. Please try again.",
      patreon_token_exchange: "Couldn't exchange the Patreon authorisation. Try again.",
      patreon_identity: "Patreon authenticated but we couldn't load your tier information.",
      patreon_no_tier: "Signed in to Patreon, but your current pledge doesn't grant any of the configured tiers.",
      patreon_misconfigured: "Patreon login is misconfigured for this deploy.",
      patreon_failed: "Patreon sign-in failed.",
      oidc_state_mismatch: "Sign-in expired or was tampered with. Please try again.",
      oidc_token_exchange: "Couldn't complete sign-in with the identity provider. Try again.",
      oidc_identity: "Signed in, but the identity provider didn't return an email address.",
      oidc_no_role: "Signed in, but your account isn't authorized for any role here.",
      oidc_misconfigured: "Single sign-on is misconfigured for this deploy.",
      oidc_failed: "Sign-in failed.",
    };
    el.textContent = messages[err] || "Sign-in failed.";
    el.hidden = false;
  }
  // Show the Patreon button only if the build emitted a roles list for it
  // (i.e. patreon is configured AND at least one role has a tier mapping).
  const card = document.querySelector(".login-card");
  if (card.dataset.patreonRoles) {
    const section = document.getElementById("patreon-section");
    section.hidden = false;
    document.getElementById("patreon-btn").href = "/auth/patreon/start?next=" + encodeURIComponent(next);
  }
  // Same pattern for OIDC: the build stamps data-oidc with the provider's
  // display name when configured with at least one role rule.
  if (card.dataset.oidc) {
    document.getElementById("oidc-section").hidden = false;
    const oidcBtn = document.getElementById("oidc-btn");
    oidcBtn.textContent = "Sign in with " + card.dataset.oidc;
    oidcBtn.href = "/auth/oidc/start?next=" + encodeURIComponent(next);
  }
  // Each provider section leads with an "or" divider, which only reads
  // correctly as an alternative to the password form. With no form, the
  // first provider is the only way in, so its divider comes off.
  if (!document.getElementById("login-form")) {
    const sections = [document.getElementById("patreon-section"), document.getElementById("oidc-section")];
    const first = sections.find((s) => s && !s.hidden);
    if (first) {
      const divider = first.querySelector(".login-divider");
      if (divider) divider.remove();
    }
  }
  // Autofocus moved here so it picks the right field whether the password
  // form is visible or the user is going for the Patreon button.
  const pwd = document.getElementById("password");
  if (pwd && !err) pwd.focus();
</script>
</body>
</html>`;
