// The Pages Function shipped to Cloudflare. Generated at build time with the
// role list and password hashes baked in. Validates session cookies, redirects
// to /login on a missing/expired cookie, and rewrites every request to the
// matching `_variants/<role>/` path before letting Pages serve it.

import { htmlAttr, htmlEscape } from "../escape.js";

export interface AuthTemplateConfig {
  /** ordered low → high */
  roles: string[];
  /**
   * Whether this deploy ships the Foundry integration. When false the bulk
   * read endpoints the Foundry module syncs through are not emitted at all —
   * a vault with no Foundry involvement should not expose them.
   */
  foundry: boolean;
  /** role → encoded password hash ("iter:saltHex:hashHex"); only for roles above the default. */
  rolePasswords: Record<string, string>;
  /**
   * Optional Patreon overlay. When present, the Function adds a
   * /auth/patreon/start + /auth/patreon/callback flow that issues the
   * same session cookie as password login. The login page also gains a
   * "Sign in with Patreon" button. Independent of password auth: a role
   * can have either, both, or just a password.
   */
  patreon?: {
    clientId: string;
    campaignId: string;
    /** role name → Patreon tier ID (numeric string) */
    tiers: Record<string, string>;
  };
  /**
   * Optional generic OIDC overlay (any standards-compliant issuer: the
   * endpoints are resolved from discovery at configure time and baked in).
   * When present, the Function adds /auth/oidc/start + /auth/oidc/callback
   * and the login page gains a "Sign in with <displayName>" button. Role
   * assignment walks roleRules from the highest role down and grants the
   * first whose email/domain rule matches the identity's email.
   */
  oidc?: {
    displayName: string;
    clientId: string;
    authorizationEndpoint: string;
    tokenEndpoint: string;
    userinfoEndpoint: string;
    /** role name → email/domain rule; roles absent here stay password-only. */
    roleRules: Record<string, { emails?: string[]; domains?: string[] }>;
  };
}

export function renderAuthMiddleware(cfg: AuthTemplateConfig): string {
  const rolesLiteral = JSON.stringify(cfg.roles);
  const passwordsLiteral = JSON.stringify(cfg.rolePasswords);
  const patreonLiteral = JSON.stringify(cfg.patreon ?? null);
  const oidcLiteral = JSON.stringify(cfg.oidc ?? null);
  const foundryLiteral = JSON.stringify(!!cfg.foundry);

  return `// Auto-generated by the vaults CLI. Do not edit by hand.
// Roles, password hashes, and routing live here so the deployed Function
// is fully self-contained and doesn't need any other binding besides
// SESSION_SECRET (set via wrangler secret). When Patreon is configured,
// PATREON_CLIENT_SECRET also has to be set as a Wrangler secret; when
// OIDC is configured, OAUTH_CLIENT_SECRET likewise.

const ROLES = ${rolesLiteral};
const PASSWORDS = ${passwordsLiteral};
const PATREON = ${patreonLiteral};
const OIDC = ${oidcLiteral};
// False on a deploy that opted out of the Foundry integration; the /_batch
// endpoints below are the API its module syncs through and nothing else uses.
const FOUNDRY = ${foundryLiteral};
const COOKIE_NAME = "vault_role";
// Non-HttpOnly companion cookie carrying the role name only; the auth check
// uses COOKIE_NAME (which is signed and HttpOnly), this one is purely for UI.
const DISPLAY_COOKIE_NAME = "vault_role_display";
const COOKIE_MAX_AGE = 60 * 60 * 24 * 7; // 7 days
// Bearer tokens (used by Foundry, MCP clients) get a much longer lifetime
// since refreshing means reopening a browser-based approval flow.
const BEARER_MAX_AGE = 60 * 60 * 24 * 90; // 90 days
// Long enough to paste a URL somewhere and press install, short enough that a
// leaked one is worthless. Deliberately not single-use: a use-count needs
// server-side state, and this deploy has none by design, so the honest
// stateless equivalent is a small window. Pre-signed URLs everywhere else
// work the same way for the same reason.
const LINK_MAX_AGE = 60 * 10; // 10 minutes
// Tokens carry their purpose so the two are not interchangeable: without
// this a 7-day session cookie and a 90-day bearer were byte-identical in
// format, so either could be replayed as the other.
const TOKEN_TYPE_SESSION = "s";
const TOKEN_TYPE_BEARER = "b";
// A link token. Separate from a bearer because it is honoured on ordinary
// navigation, which a bearer deliberately is not — see readRole.
const TOKEN_TYPE_LINK = "l";
const PBKDF2_DEFAULT_ITERATIONS = 100000;
// Same shape as a real PBKDF2 hash (iterations:saltHex:hashHex with the
// expected lengths) but with all-zero salt + hash. Used to keep the
// /login response time consistent when the role doesn't exist or has no
// password — running PBKDF2 against this dummy means an attacker can't
// distinguish "role exists" from "role doesn't exist" by timing.
const DUMMY_PASSWORD_HASH = "100000:" + "0".repeat(32) + ":" + "0".repeat(64);

// ── Public middleware entry ────────────────────────────────────────────────

export const onRequest = async (ctx) => {
  return withSecurityHeaders(await handleRequest(ctx));
};

/**
 * Headers every response gets, added at the one exit so redirects and error
 * responses are covered too.
 *
 * Referrer-Policy is load-bearing here rather than hygiene: the Foundry sync
 * passes its bearer as ?_token= in the URL, and without this any external
 * link on a page fetched that way would carry the token in the Referer.
 */
function withSecurityHeaders(response) {
  const out = new Response(response.body, response);
  out.headers.set("Referrer-Policy", "no-referrer");
  out.headers.set("X-Content-Type-Options", "nosniff");
  return out;
}

const handleRequest = async (ctx) => {
  const { request, env, next } = ctx;
  const url = new URL(request.url);

  // CORS preflight. Foundry, the MCP server, and AI tooling fetch the
  // manifest / source / search endpoints from a different origin with an
  // 'Authorization: Bearer' header, which triggers a preflight OPTIONS.
  // Allow * because the resource is gated by the bearer token, not by
  // the origin (and we don't want to maintain an allowlist).
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders() });
  }

  // Block direct access to /_variants/<role>/*; those paths exist in storage
  // for the rewrite below, but exposing them would let anyone fetch any
  // variant's manifest, page, or markdown source by guessing the role name.
  if (url.pathname.startsWith("/_variants/")) {
    return withCors(new Response("Not found", { status: 404 }), request);
  }

  // /login. POST validates a password and sets the session cookie. GET
  // serves the static login page from the deploy root; we have to pass it
  // through explicitly because the variant-rewrite below would otherwise
  // try to fetch /_variants/<role>/login (which doesn't exist).
  if (url.pathname === "/login") {
    if (request.method === "POST") return handleLogin(request, env);
    return next();
  }
  if (url.pathname === "/logout") {
    const headers = new Headers({ Location: safeNext(url.searchParams.get("next")) });
    // Emit the cookie-clear in two variants so we delete the cookie
    // regardless of which form was set: the new SameSite=None+Partitioned
    // form (used by current iframes / direct browsing), and the old
    // SameSite=Lax form (in case the cookie predates the partition switch).
    for (const name of [COOKIE_NAME, DISPLAY_COOKIE_NAME]) {
      for (const variant of clearCookieVariants(name)) {
        headers.append("Set-Cookie", variant);
      }
    }
    return new Response(null, { status: 302, headers });
  }

  // /connect. OAuth-style approval flow for Foundry / MCP clients to obtain
  // a long-lived bearer token. GET shows the approval page; POST signs the
  // token and redirects back to the requesting app.
  if (url.pathname === "/connect" && request.method === "GET") {
    return handleConnectGet(request, env);
  }
  if (url.pathname === "/connect/approve" && request.method === "POST") {
    return handleConnectApprove(request, env);
  }

  // /_link. Mints a short-lived, self-authenticating URL for one path, for
  // consumers that cannot carry the session cookie. Foundry's module
  // installer is the motivating one: it runs on the Foundry server, not in
  // the browser, so it needs a URL that stands on its own.
  if (url.pathname === "/_link" && request.method === "GET") {
    return handleLink(request, env);
  }

  // /auth/patreon/* — only mounted when the build saw a Patreon config.
  // Issues the same signed session cookie as password login on success;
  // failure paths bounce back to /login with an error param.
  if (PATREON) {
    if (url.pathname === "/auth/patreon/start" && request.method === "GET") {
      return handlePatreonStart(request, env);
    }
    if (url.pathname === "/auth/patreon/callback" && request.method === "GET") {
      return handlePatreonCallback(request, env);
    }
  }

  // /auth/oidc/* — only mounted when the build saw an OIDC config with at
  // least one role rule. Same session-cookie contract as password login.
  if (OIDC) {
    if (url.pathname === "/auth/oidc/start" && request.method === "GET") {
      return handleOidcStart(request, env);
    }
    if (url.pathname === "/auth/oidc/callback" && request.method === "GET") {
      return handleOidcCallback(request, env);
    }
  }

  // /_batch; bulk source fetch for sync clients (Foundry). Body is
  // newline-separated paths under text/plain so the request stays CORS-
  // simple (no preflight per file → no OPTIONS rate-limit). Response is
  // JSON: { files: { path: content }, missing: [path, ...] }.
  if (FOUNDRY && url.pathname === "/_batch" && request.method === "POST") {
    return withCors(await handleBatch(request, env), request);
  }

  // /_batch-images; bulk *binary* fetch (images, etc). Same input shape as
  // /_batch but each file is base64-encoded so it can ride in JSON. Used by
  // the Foundry image cache so a 300-image sync is a handful of HTTP calls
  // instead of 300 GETs that hit Cloudflare's per-IP rate limit.
  if (FOUNDRY && url.pathname === "/_batch-images" && request.method === "POST") {
    return withCors(await handleBatchBinary(request, env), request);
  }

  // Skip rewriting for static-asset paths that don't have a per-role variant.
  // Anything outside the variant tree (images, css, login page, search index
  // for the default role on root, etc.) is served as-is by Pages.
  if (isSharedAsset(url.pathname)) return next();

  // Determine the user's role from the session cookie (default = lowest).
  const role = await readRole(request, env);

  // Installing a Foundry module is two fetches: the manifest, then the zip its
  // download field names. A gated manifest is a static file, so it cannot
  // carry a live token for that second fetch, and the zip would 401 — the
  // install fails halfway with nothing useful said about why.
  //
  // So a manifest fetched with a link token gets its download URL signed to
  // match, with the same short expiry. The rewrite only ever fires when a
  // valid link token is present and the field points back at this site, so it
  // cannot be used to attach our signature to somebody else's URL.
  const linkToken = new URL(request.url).searchParams.get("_token");
  const linkRole = linkToken
    ? await verifyToken(linkToken, env.SESSION_SECRET, TOKEN_TYPE_LINK)
    : null;

  // env.ASSETS canonicalizes URLs (strips .html, strips index.html, redirects
  // with 308s); passing those redirects through to the browser would expose
  // the /_variants/<role>/ path, which the guard at the top of this function
  // explicitly blocks. So: rewrite to a clean URL, and if ASSETS still returns
  // a redirect, follow it server-side instead of leaking it to the client.
  const target = "/_variants/" + role + (url.pathname === "/" ? "/" : url.pathname);
  let rewritten = new Request(new URL(target, url.origin).toString(), request);
  let response = await env.ASSETS.fetch(rewritten);
  if (response.status >= 300 && response.status < 400) {
    const location = response.headers.get("Location");
    if (location && location.startsWith("/_variants/")) {
      rewritten = new Request(new URL(location, url.origin).toString(), request);
      response = await env.ASSETS.fetch(rewritten);
    }
  }
  if (linkRole && response.ok && /\.json$/i.test(url.pathname)) {
    const signed = await signManifestDownload(response, url, env, linkRole);
    if (signed) return signed;
  }

  // Replace bare 404s with the variant's styled 404 page so the reader stays
  // inside the site (sidebar, search, sitemap intact). Only HTML navigation
  // requests get the page; asset/API requests get the bare 404 unchanged.
  if (response.status === 404 && wantsHtml(request)) {
    const fallback = await env.ASSETS.fetch(new URL("/_variants/" + role + "/404.html", url.origin).toString());
    if (fallback.ok) {
      return withCors(new Response(await fallback.text(), {
        status: 404,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }), request);
    }
  }
  return withCors(response, request);
};

// Headers added for cross-origin clients (Foundry module, MCP). Origin: *
// is safe because the resources are gated by bearer token, not by origin.
function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
    "Access-Control-Allow-Headers": "Authorization, Content-Type",
    "Access-Control-Max-Age": "86400",
    "Vary": "Origin",
  };
}

function withCors(response, request) {
  if (!request.headers.get("Origin")) return response;
  // Response from env.ASSETS.fetch is immutable; clone before mutating.
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(corsHeaders())) headers.set(k, v);
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

function wantsHtml(request) {
  const accept = request.headers.get("Accept") || "";
  return accept.includes("text/html") || accept === "*/*" || accept === "";
}

// ── Login ─────────────────────────────────────────────────────────────────

async function handleLogin(request, env) {
  const form = await request.formData();
  const role = String(form.get("role") || "");
  const password = String(form.get("password") || "");
  const next = safeNext(form.get("next"));

  // Generic "auth_failed" error for both "no such role / no password set"
  // and "wrong password" branches — distinct codes would let an attacker
  // enumerate which roles exist and which have passwords. Constant-time
  // PBKDF2 comparison handles the timing side; this handles the message
  // side. Run verifyPassword against a dummy hash on the no-role branch
  // so the response time profile stays roughly the same.
  const passwordHash = (ROLES.includes(role) && PASSWORDS[role])
    ? PASSWORDS[role]
    : DUMMY_PASSWORD_HASH;
  const ok = await verifyPassword(password, passwordHash);
  if (!ok || !ROLES.includes(role) || !PASSWORDS[role]) {
    return loginRedirect(next, "auth_failed");
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  return new Response(null, { status: 302, headers });
}

// Sanitise a 'next' redirect target. Only same-origin relative paths are
// allowed; anything else (absolute URLs, protocol-relative '//evil.com',
// the protected /_variants/ tree) is replaced with '/'. Prevents the login
// and logout endpoints from being weaponised as open redirects.
function safeNext(value) {
  const s = typeof value === "string" ? value : "";
  if (!s.startsWith("/")) return "/";
  if (s.startsWith("//")) return "/";
  if (s.startsWith("/_variants/")) return "/";
  return s;
}

function loginRedirect(next, error) {
  const url = "/login.html?error=" + encodeURIComponent(error) + "&next=" + encodeURIComponent(next);
  return new Response(null, { status: 302, headers: { Location: url } });
}

// ── Batch source fetch ────────────────────────────────────────────────────
//
// Bulk-read endpoint used by sync clients to avoid making one HTTP request
// per .md file. The body is newline-separated paths (text/plain, so the
// request stays CORS-simple; no preflight). The handler resolves each
// path against the caller's role variant and bundles the results into a
// single JSON response.
//
// Caps:
//   - max 200 paths per call (cap concurrent ASSETS reads inside the worker)
//   - paths must not contain '..' or query/fragment, must not start with '_'
//     (would escape the variant or hit metadata files)

const BATCH_MAX_PATHS = 200;
// Smaller cap for binary; base64 inflates ~4/3x and we don't want to
// blow the worker response budget. ~30 images at 200KB avg ≈ 8MB JSON.
const BATCH_BINARY_MAX_PATHS = 30;

async function handleBatch(request, env) {
  return handleBatchInner(request, env, BATCH_MAX_PATHS, async (res) => res.text());
}

async function handleBatchBinary(request, env) {
  return handleBatchInner(request, env, BATCH_BINARY_MAX_PATHS, async (res) => {
    return base64Encode(new Uint8Array(await res.arrayBuffer()));
  });
}

async function handleBatchInner(request, env, maxPaths, encode) {
  const role = await readRole(request, env);
  if (!ROLES.includes(role)) return batchError(401, "Unauthorized");

  let body;
  try { body = await request.text(); }
  catch { return batchError(400, "Could not read request body."); }

  const paths = body.split(/\\r?\\n/).map((s) => s.trim()).filter(Boolean);
  if (paths.length === 0) return batchError(400, "No paths in request body.");
  if (paths.length > maxPaths) return batchError(400, "Too many paths (max " + maxPaths + ").");
  for (const p of paths) {
    if (!isSafePath(p)) return batchError(400, "Invalid path: " + p);
  }

  // Which rendering to return, which is not always the caller's own.
  //
  // A page carries its own role, and the sync client marks a page readable by
  // players when that role is below the DM tier. If it then filled that page
  // with the *DM's* rendering — which is what happens when the variant is
  // always the caller's — a public page ends up holding DM content and
  // readable by players. A base view filtered by role is exactly that shape:
  // one row per creature for the DM, one for everyone else, same page.
  //
  // So a caller may ask for any variant at or below their own tier. Below,
  // because that is content they can already read; never above.
  const url = new URL(request.url);
  const requested = url.searchParams.get("role");
  let variant = role;
  if (requested !== null) {
    const wantIdx = ROLES.indexOf(requested);
    if (wantIdx === -1 || wantIdx > ROLES.indexOf(role)) {
      return batchError(403, "Cannot request that variant.");
    }
    variant = requested;
  }

  // ASSETS.fetch is internal to the worker, so fan-out is cheap.
  const entries = await Promise.all(paths.map(async (p) => {
    const target = new URL("/_variants/" + variant + "/" + encodeVariantPath(p), url.origin).toString();
    const res = await env.ASSETS.fetch(target);
    if (!res.ok) return [p, null];
    return [p, await encode(res)];
  }));

  const files = {};
  const missing = [];
  for (const [p, content] of entries) {
    if (content == null) missing.push(p);
    else files[p] = content;
  }
  return new Response(JSON.stringify({ files, missing }), {
    headers: { "Content-Type": "application/json" },
  });
}

function batchError(status, message) {
  return new Response(JSON.stringify({ error: message }), {
    status, headers: { "Content-Type": "application/json" },
  });
}

function base64Encode(bytes) {
  // btoa wants a binary string. Build it in chunks so we don't blow the
  // call-stack on String.fromCharCode for big payloads.
  let binary = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
  }
  return btoa(binary);
}

function isSafePath(p) {
  if (!p || p.length > 1024) return false;
  if (p.includes("..") || p.includes("?") || p.includes("#")) return false;
  if (p.startsWith("/") || p.startsWith("_")) return false;
  // Reject control chars / bare backslashes.
  if (/[\\x00-\\x1f]/.test(p) || p.includes("\\\\")) return false;
  return true;
}

function encodeVariantPath(p) {
  // Each segment is URI-encoded so spaces / unicode round-trip cleanly.
  return p.split("/").map(encodeURIComponent).join("/");
}

// ── Connect (OAuth-style bearer token issuance) ──────────────────────────

async function handleConnectGet(request, env) {
  const url = new URL(request.url);
  const app = url.searchParams.get("app") || "an external app";

  // Require login first; the user's role is what we're authorising. The
  // default role is the unauthenticated one, so it is the whole test —
  // any other role can only have come from a verified cookie or token.
  const role = await readRole(request, env);
  if (role === ROLES[0]) {
    // Default role; redirect to login first, come back here on success.
    const next = url.pathname + url.search;
    return new Response(null, {
      status: 302,
      headers: { Location: "/login.html?next=" + encodeURIComponent(next) },
    });
  }

  const html = renderApprovePage({ app, role });
  return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}

async function handleConnectApprove(request, env) {
  const form = await request.formData();
  const app = String(form.get("app") || "an external app");

  const role = await readRole(request, env);
  if (role === ROLES[0]) {
    // User is anonymous; reject (shouldn't reach here via normal UI flow).
    return new Response("Not signed in.", { status: 401 });
  }

  const token = await signToken(role, env.SESSION_SECRET, BEARER_MAX_AGE, TOKEN_TYPE_BEARER);
  const html = renderConnectCopyPage({ token, role, app });
  return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}

/**
 * Issue a short-lived URL for a single vault path.
 *
 * The token carries the caller's own role, so this grants nothing they could
 * not already fetch with their cookie; it only moves that authority into a
 * URL, and puts a short clock on it.
 *
 * The path is confined to this deploy: it is resolved against the origin and
 * rejected if it leaves, so a caller cannot get us to sign a link pointing at
 * somewhere else.
 */
async function handleLink(request, env) {
  const url = new URL(request.url);
  // Minting requires a session or a bearer, never a link token: otherwise one
  // leaked install URL renews itself indefinitely instead of expiring.
  const role = await readRole(request, env, { rejectLinkTokens: true });
  if (role === ROLES[0]) {
    return jsonResponse({ error: "not signed in" }, 401);
  }
  const requested = url.searchParams.get("path") || "";
  if (!requested) {
    return jsonResponse({ error: "missing path" }, 400);
  }
  let target;
  try {
    target = new URL(requested, url.origin);
  } catch {
    return jsonResponse({ error: "bad path" }, 400);
  }
  if (target.origin !== url.origin) {
    return jsonResponse({ error: "path must be on this site" }, 400);
  }
  const token = await signToken(role, env.SESSION_SECRET, LINK_MAX_AGE, TOKEN_TYPE_LINK);
  target.searchParams.set("_token", token);
  return jsonResponse({
    url: target.toString(),
    role,
    expiresInMinutes: Math.round(LINK_MAX_AGE / 60),
  }, 200);
}

/**
 * Re-sign a module manifest's download URL so the second half of a Foundry
 * install authenticates too.
 *
 * Returns null and leaves the response untouched for anything that is not a
 * manifest with a same-origin download field, so an ordinary JSON asset
 * fetched with a link token is served exactly as stored.
 */
async function signManifestDownload(response, url, env, role) {
  let manifest;
  try { manifest = await response.clone().json(); }
  catch { return null; }
  if (!manifest || typeof manifest.download !== "string") return null;

  // Relative resolves onto whichever host this request arrived on, which is
  // the point: a vault can be served from several (a pages.dev name and a
  // custom domain), and a manifest that hard-codes one of them is wrong on
  // the others whether or not tokens are involved.
  //
  // An absolute URL naming a different host is left alone. That is the guard
  // against attaching our signature to somebody else's URL, and it cannot
  // distinguish the vault's own second hostname from anyone else's — so a
  // manifest that hard-codes the pages.dev name will not be signed when
  // fetched over the custom domain. Write the field relative. The CLI warns
  // when it is not.
  let target;
  try { target = new URL(manifest.download, url.origin); }
  catch { return null; }
  if (target.origin !== url.origin) return null;

  const token = await signToken(role, env.SESSION_SECRET, LINK_MAX_AGE, TOKEN_TYPE_LINK);
  target.searchParams.set("_token", token);
  manifest.download = target.toString();
  return new Response(JSON.stringify(manifest), {
    status: 200,
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });
}

function jsonResponse(body, status) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });
}

function renderApprovePage({ app, role }) {
  const escapedApp = escHtml(app);
  const escapedRole = escHtml(role);
  const escapedAppAttr = escAttr(app);
  return \`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Authorize \${escapedApp}</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .approve-card {
    max-width: 28rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .approve-card h1 { margin: 0 0 1rem; font-size: 1.4rem; }
  .approve-card .info { color: var(--muted); font-size: 0.9rem; margin: 0 0 0.75rem; }
  .approve-card .info strong { color: var(--accent); }
  .approve-card .actions { display: flex; gap: 0.75rem; margin-top: 1.25rem; }
  .approve-card button, .approve-card .deny {
    flex: 1; padding: 0.55rem 1rem; font: inherit; font-size: 0.95rem;
    border: 1px solid var(--rule); border-radius: 4px; cursor: pointer;
    text-align: center; text-decoration: none;
  }
  .approve-card button { background: var(--accent); color: var(--accent-fg); border-color: var(--accent); }
  .approve-card .deny { background: var(--bg); color: var(--muted); }
</style>
</head>
<body>
<form class="approve-card" method="POST" action="/connect/approve">
  <h1>Authorize \${escapedApp}</h1>
  <p class="info">
    <strong>\${escapedApp}</strong> wants access to your vault as
    <strong>\${escapedRole}</strong>.
  </p>
  <p class="info">After approval, this page will display a token to copy and paste back into <strong>\${escapedApp}</strong>.</p>
  <input type="hidden" name="app" value="\${escapedAppAttr}">
  <div class="actions">
    <a class="deny" href="/">Deny</a>
    <button type="submit">Approve</button>
  </div>
</form>
</body>
</html>\`;
}

function renderConnectCopyPage({ token, role, app }) {
  const escapedApp = escHtml(app);
  const escapedRole = escHtml(role);
  const escapedToken = escAttr(token);
  return \`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Authorised \${escapedApp}</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .copy-card {
    max-width: 32rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .copy-card h1 { margin: 0 0 0.75rem; font-size: 1.3rem; }
  .copy-card .info { color: var(--muted); font-size: 0.9rem; margin: 0 0 0.75rem; }
  .copy-card .info strong { color: var(--accent); }
  .copy-card .token {
    display: block; width: 100%; box-sizing: border-box;
    margin: 0.75rem 0;
    padding: 0.75rem 0.85rem;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 0.82rem; line-height: 1.45;
    background: var(--wikilink-bg);
    color: var(--fg);
    border: 1px solid var(--rule); border-radius: 4px;
    word-break: break-all; resize: vertical;
  }
  .copy-card .copy-btn {
    width: 100%; padding: 0.6rem 1rem; margin-top: 0.5rem; font: inherit; font-size: 0.95rem;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px; cursor: pointer;
  }
  .copy-card .copy-status {
    text-align: center; color: var(--muted); font-size: 0.78rem; margin-top: 0.5rem; min-height: 1em;
  }
  .copy-card .copy-status.ok { color: #2a8b58; }
  .copy-card ol { font-size: 0.88rem; color: var(--muted); padding-left: 1.25rem; margin: 0.75rem 0 0; }
  .copy-card ol li { margin: 0.25rem 0; }
</style>
</head>
<body>
<div class="copy-card">
  <h1>✓ Authorised \${escapedApp}</h1>
  <p class="info">
    A token for the <strong>\${escapedRole}</strong> tier has been generated.
    Copy it back into <strong>\${escapedApp}</strong> to complete sign-in.
  </p>
  <textarea class="token" id="token" readonly rows="4" onclick="this.select()">\${escapedToken}</textarea>
  <button type="button" class="copy-btn" id="copy-btn">Copy token</button>
  <p class="copy-status" id="copy-status"></p>
  <ol>
    <li>Click <strong>Copy token</strong> above.</li>
    <li>Switch back to \${escapedApp}.</li>
    <li>Paste into the token field and confirm.</li>
  </ol>
</div>
<script>
(function () {
  var btn = document.getElementById('copy-btn');
  var ta = document.getElementById('token');
  var status = document.getElementById('copy-status');
  btn.addEventListener('click', async function () {
    try {
      await navigator.clipboard.writeText(ta.value);
      status.textContent = 'Copied to clipboard.';
      status.className = 'copy-status ok';
    } catch (e) {
      ta.select();
      status.textContent = 'Press Ctrl/Cmd-C to copy.';
      status.className = 'copy-status';
    }
    setTimeout(function () { status.textContent = ''; }, 4000);
  });
})();
</script>
</body>
</html>\`;
}

// These two helpers are intentionally inline and not imported: this file
// generates a Cloudflare Pages Function as a string template, so the
// emitted worker can't \`import\` from cli/src/escape.ts at runtime. Keep the
// behaviour in sync with the canonical helpers in cli/src/escape.ts; the
// \`auth-template escape helpers stay in sync\` test in
// cli/test/handlers.test.ts asserts the source strings match.
function escHtml(s) { return String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c])); }
function escAttr(s) { return String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

// ── Patreon OAuth (optional, additive to password login) ─────────────────
// Bound only when PATREON !== null (i.e. the build saw a configured
// patreon block with at least one role mapped to a tier). Issues the same
// signed session cookie as password login on success; bounces back to
// /login with an error param on failure. CSRF state rides through a short-
// lived signed cookie so the callback can verify the round-trip.

// Shared by the Patreon and OIDC flows; only one OAuth round-trip can be in
// flight per browser at a time, and the state UUID check keeps a callback
// from one flow from completing the other's.
const STATE_COOKIE = "vault_oauth_state";
const STATE_TTL = 600; // 10 minutes — long enough for the user to authorise

async function handlePatreonStart(request, env) {
  if (!env.PATREON_CLIENT_SECRET) {
    return new Response("Patreon login is misconfigured: PATREON_CLIENT_SECRET secret is missing.", { status: 500 });
  }
  const url = new URL(request.url);
  const next = safeNext(url.searchParams.get("next"));
  // Bind state to next so a forged callback can't drop the user on an
  // attacker-chosen URL post-login. The signed cookie carries both back.
  const stateValue = crypto.randomUUID();
  const stateCookie = await signStateCookie({ state: stateValue, next }, env.SESSION_SECRET);

  const redirectUri = url.origin + "/auth/patreon/callback";
  const authorize = new URL("https://www.patreon.com/oauth2/authorize");
  authorize.searchParams.set("response_type", "code");
  authorize.searchParams.set("client_id", PATREON.clientId);
  authorize.searchParams.set("redirect_uri", redirectUri);
  authorize.searchParams.set("scope", "identity identity.memberships");
  authorize.searchParams.set("state", stateValue);

  const headers = new Headers({ Location: authorize.toString() });
  headers.append("Set-Cookie", stateCookie);
  return new Response(null, { status: 302, headers });
}

async function handlePatreonCallback(request, env) {
  if (!env.PATREON_CLIENT_SECRET) {
    return loginRedirect("/", "patreon_misconfigured");
  }
  const url = new URL(request.url);
  const code = url.searchParams.get("code");
  const state = url.searchParams.get("state");
  if (!code || !state) return loginRedirect("/", "patreon_failed");

  const stateData = await readStateCookie(request, env.SESSION_SECRET);
  // Always clear the state cookie regardless of outcome.
  const clearState = clearCookieVariants(STATE_COOKIE);

  if (!stateData || stateData.state !== state) {
    const headers = new Headers({ Location: "/login?error=patreon_state_mismatch" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }
  const next = stateData.next || "/";

  // Exchange code → access token. The token is short-lived; we don't store
  // it. Only used once, immediately, to look up the visitor's memberships.
  let access;
  try {
    access = await patreonExchangeCode(code, url.origin + "/auth/patreon/callback", env.PATREON_CLIENT_SECRET);
  } catch (err) {
    console.warn("Patreon token exchange failed:", err);
    const headers = new Headers({ Location: "/login?error=patreon_token_exchange" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  let identity;
  try { identity = await patreonFetchIdentity(access); }
  catch (err) {
    console.warn("Patreon identity fetch failed:", err);
    const headers = new Headers({ Location: "/login?error=patreon_identity" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const role = matchHighestRole(identity, PATREON.campaignId, PATREON.tiers);
  if (!role) {
    // Authenticated, but no qualifying tier on this campaign. Send them
    // back to /login with a specific error so the UI can explain.
    const headers = new Headers({ Location: "/login?error=patreon_no_tier&next=" + encodeURIComponent(next) });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  for (const v of clearState) headers.append("Set-Cookie", v);
  return new Response(null, { status: 302, headers });
}

/**
 * Walk the visitor's identity payload, find memberships scoped to OUR
 * campaign, and return the highest-ranked role whose mapped tier ID
 * appears in the visitor's currently-entitled tiers. Returns null if no
 * tier matches — the visitor may be a patron of someone else, or the
 * creator's own account, or just not entitled to any mapped tier.
 */
function matchHighestRole(identity, campaignId, tiers) {
  const memberships = (identity?.included || []).filter((it) => it.type === "member");
  // Filter to memberships on our campaign (Patreon nests campaign under relationships).
  const ourCampaignMemberships = memberships.filter((m) => {
    const camp = m.relationships?.campaign?.data;
    return camp && camp.type === "campaign" && String(camp.id) === String(campaignId);
  });
  const entitledTierIds = new Set();
  for (const m of ourCampaignMemberships) {
    const ents = m.relationships?.currently_entitled_tiers?.data || [];
    for (const t of ents) if (t.type === "tier") entitledTierIds.add(String(t.id));
  }
  if (entitledTierIds.size === 0) return null;
  // Roles are ordered low → high; iterate from highest to find the best match.
  for (let i = ROLES.length - 1; i >= 0; i--) {
    const r = ROLES[i];
    const tier = tiers[r];
    if (tier && entitledTierIds.has(String(tier))) return r;
  }
  return null;
}

async function patreonExchangeCode(code, redirectUri, clientSecret) {
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    code,
    client_id: PATREON.clientId,
    client_secret: clientSecret,
    redirect_uri: redirectUri,
  });
  const res = await fetch("https://www.patreon.com/api/oauth2/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });
  if (!res.ok) throw new Error("token exchange status " + res.status);
  const data = await res.json();
  if (!data.access_token) throw new Error("no access_token in response");
  return data.access_token;
}

async function patreonFetchIdentity(accessToken) {
  // We need the visitor's memberships AND, for each membership, which tiers
  // they're currently entitled to. Patreon's JSON:API include syntax pulls
  // both into one round-trip.
  const url = new URL("https://www.patreon.com/api/oauth2/v2/identity");
  url.searchParams.set("include", "memberships,memberships.currently_entitled_tiers,memberships.campaign");
  url.searchParams.set("fields[member]", "patron_status");
  const res = await fetch(url.toString(), {
    headers: { Authorization: "Bearer " + accessToken },
  });
  if (!res.ok) throw new Error("identity status " + res.status);
  return await res.json();
}

// ── OIDC OAuth (optional, additive to password login) ────────────────────
// Bound only when OIDC !== null (i.e. the build saw an oidc block with at
// least one role rule). Standard authorization-code flow with PKCE (S256):
// the code_verifier rides in the signed state cookie, the challenge goes to
// the authorization endpoint. Identity comes from the userinfo endpoint;
// the visitor's email is matched against per-role email/domain rules.

async function handleOidcStart(request, env) {
  if (!env.OAUTH_CLIENT_SECRET) {
    return new Response("OIDC login is misconfigured: OAUTH_CLIENT_SECRET secret is missing.", { status: 500 });
  }
  const url = new URL(request.url);
  const next = safeNext(url.searchParams.get("next"));
  const stateValue = crypto.randomUUID();
  const verifier = base64UrlEncode(crypto.getRandomValues(new Uint8Array(32)));
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier));
  const challenge = base64UrlEncode(new Uint8Array(digest));
  const stateCookie = await signStateCookie({ state: stateValue, next, verifier }, env.SESSION_SECRET);

  const authorize = new URL(OIDC.authorizationEndpoint);
  authorize.searchParams.set("response_type", "code");
  authorize.searchParams.set("client_id", OIDC.clientId);
  authorize.searchParams.set("redirect_uri", url.origin + "/auth/oidc/callback");
  authorize.searchParams.set("scope", "openid email");
  authorize.searchParams.set("state", stateValue);
  authorize.searchParams.set("code_challenge", challenge);
  authorize.searchParams.set("code_challenge_method", "S256");

  const headers = new Headers({ Location: authorize.toString() });
  headers.append("Set-Cookie", stateCookie);
  return new Response(null, { status: 302, headers });
}

async function handleOidcCallback(request, env) {
  if (!env.OAUTH_CLIENT_SECRET) {
    return loginRedirect("/", "oidc_misconfigured");
  }
  const url = new URL(request.url);
  const code = url.searchParams.get("code");
  const state = url.searchParams.get("state");
  if (!code || !state) return loginRedirect("/", "oidc_failed");

  const stateData = await readStateCookie(request, env.SESSION_SECRET);
  // Always clear the state cookie regardless of outcome.
  const clearState = clearCookieVariants(STATE_COOKIE);

  if (!stateData || stateData.state !== state) {
    const headers = new Headers({ Location: "/login?error=oidc_state_mismatch" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }
  const next = stateData.next || "/";

  // Exchange code → access token; used once, immediately, for userinfo.
  let access;
  try {
    access = await oidcExchangeCode(code, url.origin + "/auth/oidc/callback", env.OAUTH_CLIENT_SECRET, stateData.verifier);
  } catch (err) {
    console.warn("OIDC token exchange failed:", err);
    const headers = new Headers({ Location: "/login?error=oidc_token_exchange" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  let email;
  try { email = await oidcFetchEmail(access); }
  catch (err) {
    console.warn("OIDC userinfo fetch failed:", err);
    const headers = new Headers({ Location: "/login?error=oidc_identity" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const role = matchOidcRole(email, OIDC.roleRules);
  if (!role) {
    // Authenticated, but no rule grants this email a role.
    const headers = new Headers({ Location: "/login?error=oidc_no_role&next=" + encodeURIComponent(next) });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  for (const v of clearState) headers.append("Set-Cookie", v);
  return new Response(null, { status: 302, headers });
}

// Duplicated from cli/src/render/oidc-match.ts — the worker can't import TS
// modules, so keep the two copies in sync. Matching is exact and case-
// insensitive; a domain rule matches only the exact domain after the last
// '@' (subdomains are not implied).
function matchOidcRole(email, roleRules) {
  const at = email.lastIndexOf("@");
  if (at < 0) return null;
  const lower = email.toLowerCase();
  const domain = lower.slice(at + 1);
  for (let i = ROLES.length - 1; i >= 0; i--) {
    const rule = roleRules[ROLES[i]];
    if (!rule) continue;
    if ((rule.emails || []).some((e) => e.toLowerCase() === lower)) return ROLES[i];
    if (domain && (rule.domains || []).some((d) => d.toLowerCase() === domain)) return ROLES[i];
  }
  return null;
}

async function oidcExchangeCode(code, redirectUri, clientSecret, verifier) {
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    code,
    client_id: OIDC.clientId,
    client_secret: clientSecret,
    redirect_uri: redirectUri,
    code_verifier: verifier || "",
  });
  const res = await fetch(OIDC.tokenEndpoint, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });
  if (!res.ok) throw new Error("token exchange status " + res.status);
  const data = await res.json();
  if (!data.access_token) throw new Error("no access_token in response");
  return data.access_token;
}

async function oidcFetchEmail(accessToken) {
  const res = await fetch(OIDC.userinfoEndpoint, {
    headers: { Authorization: "Bearer " + accessToken },
  });
  if (!res.ok) throw new Error("userinfo status " + res.status);
  const data = await res.json();
  if (typeof data.email !== "string" || !data.email) throw new Error("userinfo returned no email");
  return data.email;
}

function base64UrlEncode(bytes) {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\\+/g, "-").replace(/\\//g, "_").replace(/=+$/, "");
}

/** Inverse of base64UrlEncode for UTF-8 text. */
function base64UrlDecodeUtf8(s) {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/");
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}

// State cookie: stores { state, next } (plus the PKCE verifier for OIDC)
// signed with SESSION_SECRET, used to verify the OAuth callback came from
// our /start handler and not a forgery. Shared by both OAuth flows.
// Lifetime is short (STATE_TTL); kept distinct from the long-lived
// session cookie so a stolen state cookie can't impersonate a session.

async function signStateCookie(payload, secret) {
  const exp = Math.floor(Date.now() / 1000) + STATE_TTL;
  const data = JSON.stringify({ ...payload, exp });
  const sig = await hmac(data, secret);
  // The payload carries the next path, and btoa throws on any code point
  // above U+00FF — so a page whose name uses a non-Latin1 character
  // (Sunawi with a w-circumflex, Ordogok, Japanese) turned the /start
  // handler into an unhandled 500. Encode the UTF-8 bytes instead.
  // (No backticks in this comment: it is inside the middleware template.)
  const value = base64UrlEncode(new TextEncoder().encode(data)) + "." + sig;
  return STATE_COOKIE + "=" + value
    + "; Path=/; Secure; SameSite=Lax; HttpOnly; Max-Age=" + STATE_TTL;
}

async function readStateCookie(request, secret) {
  const cookies = parseCookie(request.headers.get("Cookie") || "");
  const raw = cookies[STATE_COOKIE];
  if (!raw) return null;
  const dot = raw.lastIndexOf(".");
  if (dot < 0) return null;
  const dataB64 = raw.slice(0, dot);
  const sig = raw.slice(dot + 1);
  let data;
  try { data = base64UrlDecodeUtf8(dataB64); }
  catch { return null; }
  const expected = await hmac(data, secret);
  // Constant-time, matching verifyToken; a plain !== leaks the signature
  // byte-by-byte through response timing.
  if (!constantTimeEqual(sig, expected)) return null;
  let parsed;
  try { parsed = JSON.parse(data); }
  catch { return null; }
  if (!parsed || typeof parsed.exp !== "number" || parsed.exp < Math.floor(Date.now() / 1000)) return null;
  return parsed;
}

// ── Cookie + role lookup ──────────────────────────────────────────────────

async function readRole(request, env, opts) {
  const fallback = ROLES[0];
  if (!env.SESSION_SECRET) return fallback;

  // Authorization: Bearer <token>; used by curl / the MCP server / any
  // client that can set request headers freely. Same signed-token format
  // as the cookie, so verification is shared.
  const auth = request.headers.get("Authorization") || "";
  const bearerMatch = /^Bearer\\s+(.+)$/i.exec(auth);
  if (bearerMatch) {
    const role = await verifyToken(bearerMatch[1], env.SESSION_SECRET, TOKEN_TYPE_BEARER);
    if (role && ROLES.includes(role)) return role;
  }

  // ?_token=<token>; used by the Foundry module so cross-origin GETs stay
  // CORS-simple and don't trigger a preflight per file (Cloudflare rate-
  // limits OPTIONS bursts and a sync is hundreds of unique URLs).
  //
  // Only honoured on a request that says it is a subresource fetch. A token
  // in a URL is a shareable credential that lands in browser history, access
  // logs and Referer, and bearers last 90 days — so a pasted link must not
  // quietly browse the site at someone else's role.
  //
  // Fails CLOSED: an absent Sec-Fetch-Mode means the token is ignored. The
  // earlier version only rejected an explicit "navigate", which left the hole
  // open for anything that does not send Fetch Metadata — a proxy that strips
  // it, or a browser older than Chrome 76 / Firefox 90 / Safari 16.4. The
  // query param exists purely so the sync client's cross-origin GETs stay
  // CORS-simple, and that client is a browser, so it always sends the header.
  // Anything that cannot has no reason to prefer the param: it can set an
  // Authorization: Bearer header freely, which is checked above.
  const queryToken = new URL(request.url).searchParams.get("_token");
  if (queryToken && isSubresourceFetch(request)) {
    const role = await verifyToken(queryToken, env.SESSION_SECRET, TOKEN_TYPE_BEARER);
    if (role && ROLES.includes(role)) return role;
  }

  // A link token IS honoured on navigation, which is the whole reason it is a
  // separate type. The rule above rests on bearers lasting 90 days; a link
  // token lasts ten minutes, so the same reasoning does not reach it. It also
  // has to work this way: Foundry's module installer accepts a URL and
  // nothing else, so it cannot send the Authorization header the rule above
  // points anything header-capable towards.
  //
  // It authenticates one request and sets no cookie, so a shared link does
  // not turn into a session at someone else's role.
  // Not accepted where a caller could use one to obtain another. A link token
  // is a ten-minute grant, and a request that can mint a fresh one renews
  // itself forever — which would quietly turn the short window that justifies
  // honouring these on navigation into no window at all.
  if (queryToken && !opts?.rejectLinkTokens) {
    const role = await verifyToken(queryToken, env.SESSION_SECRET, TOKEN_TYPE_LINK);
    if (role && ROLES.includes(role)) return role;
  }

  const cookie = parseCookie(request.headers.get("Cookie") || "")[COOKIE_NAME];
  if (!cookie) return fallback;
  const role = await verifyToken(cookie, env.SESSION_SECRET, TOKEN_TYPE_SESSION);
  return role && ROLES.includes(role) ? role : fallback;
}

/**
 * True only when the request explicitly identifies itself as a subresource
 * fetch rather than a navigation. Absent headers count as "not a fetch", so
 * the caller refuses rather than guesses.
 */
function isSubresourceFetch(request) {
  const mode = request.headers.get("Sec-Fetch-Mode");
  if (!mode || mode === "navigate") return false;
  return request.headers.get("Sec-Fetch-Dest") !== "document";
}

// Format: <role>.<expiryUnix>.<hmacHex>
async function signToken(role, secret, maxAgeSeconds, typ) {
  const exp = Math.floor(Date.now() / 1000) + maxAgeSeconds;
  const payload = typ + "." + role + "." + exp;
  const sig = await hmac(payload, secret);
  return payload + "." + sig;
}

async function signSessionCookie(role, secret) {
  const value = await signToken(role, secret, COOKIE_MAX_AGE, TOKEN_TYPE_SESSION);
  // SameSite=None + Partitioned (CHIPS); required so the cookie persists
  // when the vault is loaded inside a cross-origin iframe (the Foundry
  // connect dialog). Partitioned scopes the cookie per parent origin, so
  // it isn't a general third-party tracking cookie. Top-level browsing
  // still works normally.
  return COOKIE_NAME + "=" + value
    + "; Path=/; HttpOnly; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE;
}

async function verifyToken(token, secret, expectedTyp) {
  const parts = token.split(".");
  // 4 parts is the typed form; 3 is the untyped one issued before session
  // cookies and bearers were distinguishable. Legacy tokens still verify, for
  // either purpose, so nobody is logged out by the upgrade — they age out on
  // their own within 90 days. Drop this branch after that.
  const legacy = parts.length === 3;
  if (parts.length !== 4 && !legacy) return null;
  const [typ, role, expStr, sig] = legacy ? [expectedTyp, ...parts] : parts;
  if (typ !== expectedTyp) return null;
  const exp = Number(expStr);
  if (!Number.isFinite(exp) || exp < Math.floor(Date.now() / 1000)) return null;
  const signed = legacy ? role + "." + expStr : typ + "." + role + "." + expStr;
  const expected = await hmac(signed, secret);
  return constantTimeEqual(sig, expected) ? role : null;
}

function clearCookieVariants(name) {
  // Browsers match cookies for deletion on (Path, Domain, Secure, SameSite,
  // Partitioned). A single Set-Cookie attempt only matches one configuration,
  // so we emit two; one that matches cookies set by the current
  // (SameSite=None+Partitioned) signSessionCookie, and one that matches the
  // older Lax form. Both are safe to send; the unmatched one is a no-op.
  const httpOnly = name === COOKIE_NAME ? "HttpOnly; " : "";
  return [
    name + "=; Path=/; " + httpOnly + "Secure; SameSite=None; Partitioned; Max-Age=0",
    name + "=; Path=/; " + httpOnly + "Secure; SameSite=Lax; Max-Age=0",
  ];
}

// ── Crypto primitives (Web Crypto API) ────────────────────────────────────

async function hmac(message, secretHex) {
  const keyBytes = fromHex(secretHex);
  const key = await crypto.subtle.importKey(
    "raw", keyBytes, { name: "HMAC", hash: "SHA-256" }, false, ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return toHex(new Uint8Array(sig));
}

async function verifyPassword(password, encoded) {
  const parts = encoded.split(":");
  if (parts.length !== 3) return false;
  const iterations = Number(parts[0]) || PBKDF2_DEFAULT_ITERATIONS;
  const salt = fromHex(parts[1]);
  const expected = fromHex(parts[2]);
  const key = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(password), { name: "PBKDF2" }, false, ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, hash: "SHA-256", iterations },
    key, expected.length * 8,
  );
  return constantTimeEqual(toHex(new Uint8Array(bits)), toHex(expected));
}

function constantTimeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function toHex(bytes) {
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += bytes[i].toString(16).padStart(2, "0");
  return s;
}

function fromHex(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function parseCookie(header) {
  const out = {};
  for (const part of header.split(/;\\s*/)) {
    const eq = part.indexOf("=");
    if (eq > 0) out[part.slice(0, eq)] = part.slice(eq + 1);
  }
  return out;
}

function isSharedAsset(pathname) {
  // Allowlist of root-served files that are intentionally public to every
  // visitor (no role gate). Everything else — including images, .body.html
  // fragments, .preview.json, the search index — goes through the variant
  // rewrite so role-restricted content is structurally unreachable on
  // under-tier deploys.
  //
  // SYNCHRONISATION POINT: every file the build writes to the deploy
  // ROOT (vs. into _variants/<role>/) must be listed here, otherwise it
  // 404s for every visitor. Build code that places root-level files:
  //   - styles.css / user.css        — build.ts (writeFile join(outputDir, ...))
  //   - _handlers.js / _handlers.css — build.ts (handler asset bundles, root)
  //   - katex/…                      — build.ts (copyKatexAssets; math vaults only)
  //   - _foundry/importer.js            — build.ts (foundry-importer bundle)
  //   - login.html                   — build.ts (multi-role only)
  //   - favicon.ico                  — build.ts (buildFavicon)
  //   - functions/_middleware.js     — build.ts (multi-role only; not served)
  // If you add another, add it both here AND in build.ts.
  //
  // _handlers.foundry.{js,css} is *deliberately not* listed: it lives in
  // each variant directory so the middleware rewrites root requests to
  // /_variants/<role>/_handlers.foundry.* per the requester's role,
  // gating higher-tier handler assets behind authentication the same way
  // page bodies are.
  if (pathname === "/styles.css") return true;
  if (pathname === "/user.css") return true;
  if (pathname === "/_handlers.js") return true;
  if (pathname === "/_handlers.css") return true;
  if (pathname === "/katex/katex.min.css" || pathname.startsWith("/katex/fonts/")) return true;
  if (pathname === "/_foundry/importer.js") return true;
  if (pathname === "/login.html") return true;
  if (pathname === "/favicon.ico" || pathname === "/favicon.svg") return true;
  if (pathname === "/robots.txt") return true;
  if (pathname === "/sitemap.xml") return true;
  return false;
}
`;
}

/**
 * Render `login.html` for a deploy, showing only the sign-in methods it
 * actually has.
 *
 * A role is reachable by password only if a hash was set for it; Patreon and
 * OIDC each carry their own role mappings. A deploy authenticating purely
 * through a provider therefore gets no password form and no role selector —
 * the selector only ever chose which password to check, so with one password
 * role (or none) it is noise, and with none it would be a form that cannot
 * succeed.
 */
export function renderLoginPage(opts: {
  /** Roles with a password hash, in tier order. */
  passwordRoles: string[];
  /** Roles mapped to a Patreon tier, empty when Patreon isn't configured. */
  patreonRoles: string[];
  /** OIDC provider display name, or null when OIDC isn't configured. */
  oidcDisplayName: string | null;
}): string {
  const { passwordRoles, patreonRoles, oidcDisplayName } = opts;

  let form = "";
  if (passwordRoles.length > 0) {
    // One password role means there is nothing to choose, so the role rides
    // as a hidden field and the visitor just types a password.
    const rolePicker = passwordRoles.length === 1
      ? `    <input type="hidden" name="role" value="${htmlAttr(passwordRoles[0]!)}">`
      : `    <label for="role">Role</label>\n`
        + `    <select id="role" name="role">`
        + passwordRoles.map((r) => `<option value="${htmlAttr(r)}">${htmlEscape(r)}</option>`).join("")
        + `</select>`;
    form = `  <form id="login-form" method="POST" action="/login">\n`
      + `${rolePicker}\n`
      + `    <label for="password">Password</label>\n`
      + `    <input id="password" type="password" name="password" autocomplete="current-password" required>\n`
      + `    <input type="hidden" name="next" id="next">\n`
      + `    <button type="submit">Sign in</button>\n`
      + `  </form>`;
  }

  // Replacer *functions*, not strings: a string replacement interprets `$&`
  // and friends, and oidcDisplayName is free text, so a provider named
  // "Acme $& Co" would splice the placeholder back into the page.
  const literal = (value: string) => () => value;
  return LOGIN_HTML
    .replace("__PASSWORD_FORM__", literal(form))
    .replace("__PATREON_ROLES_ATTR__", literal(patreonRoles.length > 0
      ? ` data-patreon-roles="${htmlAttr(patreonRoles.join(","))}"` : ""))
    .replace("__OIDC_ATTR__", literal(oidcDisplayName ? ` data-oidc="${htmlAttr(oidcDisplayName)}"` : ""));
}

const LOGIN_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sign in</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .login-card {
    max-width: 24rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .login-card h1 { margin: 0 0 1rem; font-size: 1.4rem; }
  .login-card label { display: block; font-size: 0.85rem; color: var(--muted); margin: 0.75rem 0 0.25rem; }
  .login-card select, .login-card input[type=password] {
    width: 100%; padding: 0.5rem 0.65rem; font: inherit; font-size: 0.95rem;
    background: var(--bg); color: var(--fg);
    border: 1px solid var(--rule); border-radius: 4px; outline: none;
  }
  .login-card select:focus, .login-card input:focus { border-color: var(--accent); box-shadow: 0 0 0 2px var(--wikilink-bg); }
  .login-card button {
    width: 100%; padding: 0.55rem 1rem; margin-top: 1rem; font: inherit;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px; cursor: pointer;
  }
  .login-error { color: #b94a3a; font-size: 0.85rem; margin: 0.75rem 0 0; }
  .login-divider {
    display: flex; align-items: center; gap: 0.6rem;
    margin: 1.25rem 0 1rem;
    font-size: 0.78rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.06em;
  }
  .login-divider::before, .login-divider::after {
    content: ""; flex: 1; height: 1px; background: var(--rule);
  }
  .patreon-btn {
    display: flex; align-items: center; justify-content: center; gap: 0.5rem;
    width: 100%; padding: 0.55rem 1rem; font: inherit; font-size: 0.95rem;
    background: #ff424d; color: white; border: 0; border-radius: 4px;
    cursor: pointer; text-decoration: none;
  }
  .patreon-btn:hover { filter: brightness(1.05); }
  .patreon-hint { color: var(--muted); font-size: 0.78rem; margin-top: 0.6rem; text-align: center; }
  .oidc-btn {
    display: flex; align-items: center; justify-content: center;
    width: 100%; padding: 0.55rem 1rem; font: inherit; font-size: 0.95rem;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px;
    cursor: pointer; text-decoration: none;
  }
  .oidc-btn:hover { filter: brightness(1.05); }
</style>
</head>
<body>
<div class="login-card"__PATREON_ROLES_ATTR____OIDC_ATTR__>
  <h1>Sign in</h1>
  <p id="err" class="login-error" hidden></p>
__PASSWORD_FORM__
  <div id="patreon-section" hidden>
    <div class="login-divider">or</div>
    <a id="patreon-btn" class="patreon-btn" href="#">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <circle cx="14.5" cy="9.5" r="6.5"/>
        <rect x="2" y="3" width="3.5" height="18"/>
      </svg>
      Sign in with Patreon
    </a>
    <p class="patreon-hint">
      Active patrons of the configured tiers can sign in directly. The role
      selector above only matters for password sign-in.
    </p>
  </div>
  <div id="oidc-section" hidden>
    <div class="login-divider">or</div>
    <a id="oidc-btn" class="oidc-btn" href="#">Sign in</a>
  </div>
</div>
<script>
  const params = new URLSearchParams(location.search);
  const next = params.get("next") || "/";
  // The password form is omitted entirely on a deploy where no role has a
  // password, so nothing here may assume its fields exist.
  const nextField = document.getElementById("next");
  if (nextField) nextField.value = next;
  const err = params.get("error");
  if (err) {
    const el = document.getElementById("err");
    const messages = {
      // Single message for any password-path failure — distinct error
      // codes would let an attacker enumerate which roles exist.
      auth_failed: "Invalid role or password.",
      patreon_state_mismatch: "Patreon sign-in expired or was tampered with. Please try again.",
      patreon_token_exchange: "Couldn't exchange the Patreon authorisation. Try again.",
      patreon_identity: "Patreon authenticated but we couldn't load your tier information.",
      patreon_no_tier: "Signed in to Patreon, but your current pledge doesn't grant any of the configured tiers.",
      patreon_misconfigured: "Patreon login is misconfigured for this deploy.",
      patreon_failed: "Patreon sign-in failed.",
      oidc_state_mismatch: "Sign-in expired or was tampered with. Please try again.",
      oidc_token_exchange: "Couldn't complete sign-in with the identity provider. Try again.",
      oidc_identity: "Signed in, but the identity provider didn't return an email address.",
      oidc_no_role: "Signed in, but your account isn't authorized for any role here.",
      oidc_misconfigured: "Single sign-on is misconfigured for this deploy.",
      oidc_failed: "Sign-in failed.",
    };
    el.textContent = messages[err] || "Sign-in failed.";
    el.hidden = false;
  }
  // Show the Patreon button only if the build emitted a roles list for it
  // (i.e. patreon is configured AND at least one role has a tier mapping).
  const card = document.querySelector(".login-card");
  if (card.dataset.patreonRoles) {
    const section = document.getElementById("patreon-section");
    section.hidden = false;
    document.getElementById("patreon-btn").href = "/auth/patreon/start?next=" + encodeURIComponent(next);
  }
  // Same pattern for OIDC: the build stamps data-oidc with the provider's
  // display name when configured with at least one role rule.
  if (card.dataset.oidc) {
    document.getElementById("oidc-section").hidden = false;
    const oidcBtn = document.getElementById("oidc-btn");
    oidcBtn.textContent = "Sign in with " + card.dataset.oidc;
    oidcBtn.href = "/auth/oidc/start?next=" + encodeURIComponent(next);
  }
  // Each provider section leads with an "or" divider, which only reads
  // correctly as an alternative to the password form. With no form, the
  // first provider is the only way in, so its divider comes off.
  if (!document.getElementById("login-form")) {
    const sections = [document.getElementById("patreon-section"), document.getElementById("oidc-section")];
    const first = sections.find((s) => s && !s.hidden);
    if (first) {
      const divider = first.querySelector(".login-divider");
      if (divider) divider.remove();
    }
  }
  // Autofocus moved here so it picks the right field whether the password
  // form is visible or the user is going for the Patreon button.
  const pwd = document.getElementById("password");
  if (pwd && !err) pwd.focus();
</script>
</body>
</html>`;
